import React,{useState,useEffect,useCallback,useRef} from 'react';
import {Plus,ImagePlus,Upload,Film,ArrowUp,ArrowDown,Trash2,Eye,Send,Copy,Save,ShieldCheck,Clock,ChevronLeft,ChevronRight,Sparkles,LoaderCircle,FolderOpen,X} from 'lucide-react';
import {useCopy,Field,Toggle,PubModal,StateBadge,ErrorNotice} from './ui';
import type {PostDraft,PostFormat} from './types';
function MediaPreview({asset,large=false}:{asset:any;large?:boolean}){
 const {api,tr}=useCopy();const [url,setUrl]=useState(''),[error,setError]=useState(false);
 useEffect(()=>{let active=true;setUrl('');setError(false);if(asset?.data.status==='ready')api('/publishing/assets/'+asset.id+'/preview').then((r:any)=>{if(active)setUrl(r.url);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[api,asset?.id,asset?.version]);
 if(!url)return <div className="pub-media-placeholder"><ImagePlus size={large?34:24}/>{error&&<small>{tr(['رسانه در دسترس نیست','Media unavailable','Medya kullanılamıyor','Медиа недоступно'])}</small>}</div>;
 return asset.data.mime.startsWith('video/')?<video src={url} controls={large} muted playsInline preload="metadata" onError={()=>{setError(true);setUrl('');}}/>:<img src={url} alt={asset.data.name} referrerPolicy="no-referrer"/>;
}
export function PostManager({cfg,agents,campaigns,onRefresh}:{cfg:any;agents:any[];campaigns:any[];onRefresh:()=>Promise<void>}){
 const {api,c,tr,staff,can,language}=useCopy();const [drafts,setDrafts]=useState<any[]>([]),[assets,setAssets]=useState<any[]>([]),[jobs,setJobs]=useState<any[]>([]),[tasks,setTasks]=useState<any[]>([]),[storage,setStorage]=useState<any>(null);
 const [editing,setEditing]=useState<any>(null),[dirty,setDirty]=useState(false),[modal,setModal]=useState<'preview'|'library'|'publish'|'generate'|null>(null),[slide,setSlide]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [uploads,setUploads]=useState<any[]>([]),[brief,setBrief]=useState(''),[publishNow,setPublishNow]=useState(true),[when,setWhen]=useState(''),[confirmed,setConfirmed]=useState(false),[agentCost,setAgentCost]=useState(false),[selected,setSelected]=useState<string[]>([]),[batchPublish,setBatchPublish]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),controllers=useRef(new Map<string,AbortController>());
 const load=useCallback(async()=>{try{const [d,a,j,g]=await Promise.all([api('/publishing/drafts'),api('/publishing/assets'),api('/publishing/publications'),api('/publishing/agent-tasks')]);setDrafts(d);setAssets(a.assets);setStorage(a.storage);setJobs(j);setTasks(g);}catch(e:any){setError(e.code||e.message);}},[api]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState!=='hidden')void load();},10000);return()=>clearInterval(timer);},[load]);
 const asset=(id:string)=>assets.find(a=>a.id===id);
 const label=(format:string)=>({image:tr(['تک‌تصویر','Single image','Tek görsel','Одно фото']),carousel:tr(['اسلایدی','Carousel','Kaydırmalı','Карусель']),reel:'Reel',story:'Story'}[format]||format);
 const update=(key:string,value:any)=>{setEditing((r:any)=>({...r,data:{...r.data,[key]:value}}));setDirty(true);setError('');};
 async function action(fn:()=>Promise<any>){setBusy(true);setError('');setSuccess('');try{const r=await fn();await load();await onRefresh();return r;}catch(e:any){setError(e.code||e.message||'OPERATION_FAILED');return null;}finally{setBusy(false);}}
 async function newDraft(){const r=await action(()=>api('/publishing/drafts','POST',{title:'',caption:'',language,format:'image',assetIds:[],campaignId:'',executionMode:cfg.config.data.selectedMode||'manual',agentId:cfg.config.data.defaultAgentId,timezone:cfg.config.data.timezone}));if(r){setEditing(r);setDirty(false);setSlide(0);}}
 async function save(){const r=await action(()=>api('/publishing/drafts/'+editing.id,'PUT',{...editing.data,version:editing.version}));if(r){setEditing(r);setDirty(false);setSuccess(tr(['پیش‌نویس ذخیره شد.','Draft saved.','Taslak kaydedildi.','Черновик сохранён.']));}return r;}
 function open(r:any){setEditing(structuredClone(r));setDirty(false);setSlide(0);setError('');setSuccess('');}
 function move(index:number,to:number){const list=[...editing.data.assetIds];if(to<0||to>=list.length)return;[list[index],list[to]]=[list[to],list[index]];update('assetIds',list);setSlide(to);}
 function selectAsset(id:string){const ids=editing.data.assetIds;if(ids.includes(id))return;
  if(editing.data.format==='carousel'){if(ids.length>=10){setError('MEDIA_COUNT_INVALID');return;}update('assetIds',[...ids,id]);}else update('assetIds',[id]);setSlide(0);
 }
 async function uploadFiles(files:File[],resume?:any){
  if(!editing)return;const targetDraftId=editing.id;
  if(files.length>1&&editing.data.format!=='carousel'){setError('SELECT_CAROUSEL_FOR_MULTIPLE');return;}
  for(const file of files){
   const uid=crypto.randomUUID(),controller=new AbortController();controllers.current.set(uid,controller);let row:any=resume;
   const patch=(data:any)=>setUploads(u=>u.map(x=>x.id===uid?{...x,...data}:x));
   setUploads(u=>[...u,{id:uid,name:file.name,progress:0,status:'uploading',file}]);
   try{
    if(resume&&(file.size!==resume.data.size||file.name!==resume.data.name))throw Error('RESUME_FILE_MISMATCH');
    if(!row)row=await api('/publishing/assets','POST',{name:file.name,mime:file.type,size:file.size});
    patch({assetId:row.id});let offset=row.data.received||0;
    while(offset<file.size){
      if(controller.signal.aborted)throw Error('UPLOAD_CANCELLED');
      const chunk=file.slice(offset,Math.min(file.size,offset+(storage?.chunkBytes||4*1024*1024)));
      const response=await fetch(`/api/management/publishing/assets/${row.id}/chunks/${offset}`,{method:'PUT',headers:{'Content-Type':'application/octet-stream',Authorization:`Bearer ${localStorage.getItem('bazino.authToken')||''}`},body:chunk,signal:controller.signal});
      const out=await response.json();if(!response.ok)throw Error(out.error||'UPLOAD_FAILED');offset=out.received;patch({progress:Math.round(offset/file.size*100)});
    }
    patch({status:'validating'});const ready=await api('/publishing/assets/'+row.id+'/complete','POST',{});
    if(controller.signal.aborted){await api('/publishing/assets/'+row.id,'DELETE');throw Error('UPLOAD_CANCELLED');}
    setAssets(a=>[...a.filter(x=>x.id!==ready.id),ready]);
    setEditing((r:any)=>!r||r.id!==targetDraftId?r:({...r,data:{...r.data,assetIds:r.data.format==='carousel'?[...r.data.assetIds,ready.id].slice(0,10):[ready.id]}}));setDirty(true);patch({status:'ready',progress:100});
   }catch(e:any){patch({status:controller.signal.aborted?'cancelled':'failed',error:e.code||e.message,assetId:row?.id});}
   finally{controllers.current.delete(uid);await load();}
  }
 }
 function publicationDialog(batch=false){setBatchPublish(batch);setConfirmed(false);setAgentCost(false);setPublishNow(true);setWhen('');setModal('publish');}
 async function publish(){
   const [date,time]=when.split('T');const body={confirmed,publishNow,date,time,confirmedAgentCost:agentCost};
   const result=await action(()=>batchPublish?api('/publishing/batches/schedule','POST',{...body,draftIds:selected,draftVersions:Object.fromEntries(selected.map(id=>[id,drafts.find(d=>d.id===id)?.version]))}):api('/publishing/drafts/'+editing.id+'/schedule','POST',{...body,version:editing.version}));
   if(result){setModal(null);setEditing(null);setSelected([]);setSuccess(tr(['کار انتشار ثبت شد؛ نتیجهٔ واقعی از سرویس تأیید می‌شود.','Publication queued. Actual publication is confirmed by the provider.','Yayın işi kaydedildi; gerçek sonuç servisten doğrulanır.','Публикация поставлена в очередь. Результат подтверждается сервисом.']));}
 }
 const draft=editing?.data;
 const liveAgent=agents.find(a=>a.id===draft?.agentId);
 return <div className="pub-post-manager" data-post-manager><ErrorNotice error={error}/>{success&&<p className="pub-success" role="status">{success}</p>}
 {!editing?<>
  <div className="pub-section-title"><div><h2>{tr(['پست‌ها و پیش‌نویس‌ها','Posts & drafts','Gönderiler ve taslaklar','Публикации и черновики'])}</h2><p className="pub-note">{tr(['رسانهٔ خودتان، تأیید خودتان؛ انتشار قابل پیگیری.','Your media. Your approval. Traceable publishing.','Medyanız, onayınız; izlenebilir yayın.','Ваши медиа, ваше одобрение, проверяемая публикация.'])}</p></div><button className="pub-primary" disabled={busy} onClick={newDraft} data-new-post><Plus size={16}/>{tr(['پست جدید','New post','Yeni gönderi','Новая публикация'])}</button></div>
  {selected.length>0&&<div className="pub-batch-bar"><span>{selected.length}/3 {tr(['انتخاب شده','selected','seçildi','выбрано'])}</span><button className="pub-primary" disabled={selected.length!==3||busy||!can('publish')} onClick={()=>publicationDialog(true)}>{tr(['انتشار batch سه‌تایی','Publish batch of three','Üçlü grubu yayınla','Опубликовать группу из трёх'])}</button></div>}
  <div className="pub-post-grid">{drafts.map(r=><article className="pub-post-card" key={r.id}><div className="pub-post-thumb"><MediaPreview asset={asset(r.data.assetIds[0])}/><span className="pub-format-tag">{label(r.data.format)}</span></div><div className="pub-post-card-body"><div className="pub-card-top"><StateBadge value={r.data.status}/>{r.data.campaignId&&r.data.status==='approved'&&<input type="checkbox" aria-label={tr(['انتخاب برای batch','Select for batch','Grup için seç','Выбрать для группы'])} checked={selected.includes(r.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.id]:s.filter(x=>x!==r.id))}/>}</div><h3>{r.data.title||tr(['پست بدون عنوان','Untitled post','Başlıksız gönderi','Без названия'])}</h3><p>{r.data.caption||'—'}</p><div className="pub-post-meta"><span>{r.data.executionMode==='manual'?c('manual'):c('agent')}</span><span>{r.data.language.toUpperCase()}</span><span>r{r.data.revision}</span></div><div className="pub-actions">{!['published','submitted','delivery_unknown'].includes(r.data.status)&&<button className="pub-secondary" onClick={()=>open(r)}>{c('edit')}</button>}<button className="pub-secondary" onClick={()=>action(async()=>{const copy=await api('/publishing/drafts/'+r.id+'/clone','POST',{});open(copy);})}><Copy size={13}/>{tr(['کپی پیش‌نویس','Duplicate','Kopyala','Дублировать'])}</button></div></div></article>)}</div>
  {!drafts.length&&<div className="pub-empty"><ImagePlus size={36}/><h2>{tr(['اولین پست را آماده کنید','Prepare your first post','İlk gönderinizi hazırlayın','Подготовьте первую публикацию'])}</h2><p>{tr(['عکس و ویدئو بارگذاری کنید، اسلایدها را بچینید و پیش از انتشار نتیجه را ببینید.','Upload images or video, arrange slides, and preview before publishing.','Görsel/video yükleyin, slaytları sıralayın ve yayın öncesi görün.','Загрузите фото или видео, расположите слайды и проверьте результат.'])}</p></div>}
  {!!jobs.length&&<section className="pub-card"><h2>{tr(['وضعیت انتشار','Publication status','Yayın durumu','Статус публикации'])}</h2><div className="pub-table-scroll"><table><thead><tr><th>{tr(['پست','Post','Gönderi','Публикация'])}</th><th>{c('status')}</th><th>Media ID</th><th></th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td>{j.data.title}<small className="pub-block">{j.data.provider}</small></td><td><StateBadge value={j.data.rollupStatus==='partial'?'partial':j.data.state}/>{j.data.error&&<code className="pub-block">{j.data.error}</code>}{j.data.taskUrl&&<a className="pub-block" href={j.data.taskUrl} target="_blank" rel="noopener noreferrer">{tr(['مشاهده کار عامل','Open agent task','Aracı görevini aç','Открыть задачу агента'])}</a>}</td><td dir="ltr">{j.data.nativeMediaId||'—'}{j.data.publishedUrl&&<a className="pub-block" href={j.data.publishedUrl} target="_blank" rel="noopener noreferrer">{tr(['مشاهده پست','View post','Gönderiyi aç','Открыть публикацию'])}</a>}</td><td>{can('publish')&&['submitted','delivery_unknown'].includes(j.data.state)&&<button className="pub-secondary" disabled={busy} onClick={()=>action(()=>api('/publishing/publications/'+j.id+'/reconcile','POST',{confirmed:true}))}>{tr(['بررسی نتیجه','Reconcile','Sonucu kontrol et','Проверить результат'])}</button>}{can('publish')&&j.data.state==='failed'&&<button className="pub-secondary" disabled={busy} onClick={()=>{if(confirm(tr(['تلاش مجدد فقط برای درخواست قطعاً ارسال‌نشده انجام می‌شود. ادامه؟','Retry only a definitively failed attempt. Continue?','Yalnızca kesin başarısız işlemi tekrarla. Devam?','Повторить только явно неудачную попытку?'])))void action(()=>api('/publishing/publications/'+j.id+'/retry','POST',{confirmed:true}));}}>{tr(['تلاش مجدد','Retry','Tekrar dene','Повторить'])}</button>}</td></tr>)}</tbody></table></div></section>}
 </>:<>
  <div className="pub-editor-heading"><button className="pub-secondary" onClick={()=>{if(!dirty||confirm(tr(['تغییرات ذخیره‌نشده کنار گذاشته شوند؟','Discard unsaved changes?','Kaydedilmeyen değişiklikler silinsin mi?','Отменить несохранённые изменения?'])))setEditing(null);}}>{c('back')}</button><div><h2>{draft.title||tr(['پست جدید','New post','Yeni gönderi','Новая публикация'])}</h2><span className="pub-muted">{dirty?tr(['ذخیره نشده','Unsaved changes','Kaydedilmedi','Не сохранено']):`${c('version')} ${editing.version}`}</span></div><StateBadge value={draft.status}/></div>
  <div className="pub-editor-grid"><section className="pub-card pub-editor-fields"><Field label={tr(['عنوان داخلی','Internal title','İç başlık','Внутреннее название'])}><input data-post-title value={draft.title} maxLength={200} onChange={e=>update('title',e.target.value)}/></Field><div className="pub-form-grid"><Field label={tr(['قالب انتشار','Post format','Gönderi biçimi','Формат'])}><select data-post-format value={draft.format} onChange={e=>{update('format',e.target.value);if(e.target.value==='story')update('campaignId','');}}>{['image','carousel','reel','story'].map(f=><option value={f} key={f}>{label(f)}{f==='story'?tr([' — نیازمند مجوز حساب',' — account permission required',' — hesap izni gerekli',' — нужны права аккаунта']):''}</option>)}</select></Field><Field label={tr(['زبان محتوا','Content language','İçerik dili','Язык контента'])}><select value={draft.language} onChange={e=>update('language',e.target.value)}>{['tr','fa','en','ru'].map(l=><option key={l}>{l}</option>)}</select></Field></div>
   <Field label={tr(['کپشن','Caption','Açıklama','Подпись'])} hint={tr(['خط جدید، هشتگ و منشن مجاز است؛ HTML نمایش غنی ندارد.','Line breaks, hashtags and mentions; HTML is not rich formatting.','Satır sonu, hashtag ve bahsetme; HTML zengin metin değildir.','Переносы строк, хэштеги и упоминания; HTML не форматирует текст.'])}><textarea data-post-caption rows={7} value={draft.caption} onChange={e=>update('caption',e.target.value)}/><small dir="ltr" className={[...draft.caption].length>2200?'pub-error-text':''}>{[...draft.caption].length} / 2200</small></Field>
   <div className="pub-form-grid"><Field label={tr(['روش انتشار این پست','This post’s execution mode','Bu gönderinin yayın modu','Режим этой публикации'])}><select value={draft.executionMode} onChange={e=>{update('executionMode',e.target.value);if(e.target.value==='agent')update('agentId',cfg.config.data.defaultAgentId);}}><option value="manual">{c('manual')}</option><option value="agent">{c('agent')}</option></select></Field>{draft.executionMode==='agent'&&<Field label={tr(['عامل مسئول','Assigned agent','Atanan aracı','Назначенный агент'])}><select value={draft.agentId} onChange={e=>update('agentId',e.target.value)}>{agents.map(a=><option key={a.id} value={a.id} disabled={!a.data.enabled||a.data.adapterId!=='manus'}>{a.data.name}</option>)}</select></Field>}</div>
   {draft.executionMode==='agent'&&<div className="pub-note banner"><StateBadge value={liveAgent?.status||'unconfigured'}/><p>{tr(['عامل فقط نسخهٔ تأییدشده را منتشر می‌کند؛ اتصال حساب اجتماعی او نیز باید آماده باشد.','The agent publishes only the approved snapshot; its social connector must also be authorized.','Aracı yalnızca onaylı sürümü yayınlar; sosyal bağlantısı da yetkili olmalıdır.','Агент публикует одобренную версию; его социальный коннектор должен быть авторизован.'])}</p><button className="pub-secondary" disabled={busy||dirty||liveAgent?.status!=='ready'||!can('publish')} onClick={()=>{setConfirmed(false);setModal('generate');}}><Sparkles size={14}/>{tr(['تهیه کپشن با عامل','Draft caption with agent','Aracıyla açıklama hazırla','Подготовить подпись агентом'])}</button>{tasks.filter(t=>t.draftId===editing.id).slice(0,2).map(t=><p key={t.id}><StateBadge value={t.status}/>{['queued','submitted','cancel_unknown'].includes(t.status)&&<button className="pub-secondary" onClick={()=>action(()=>api('/publishing/agent-tasks/'+t.id+'/cancel','POST',{confirmed:true}))}>{c('cancel')}</button>}{['complete','superseded'].includes(t.status)&&<button className="pub-secondary" onClick={()=>{const fresh=drafts.find(d=>d.id===editing.id);if(fresh&&!dirty)open(fresh);}}>{c('refresh')}</button>}</p>)}</div>}
   <Field label={tr(['کمپین افیلیت (اختیاری)','Affiliate campaign (optional)','Ortaklık kampanyası (isteğe bağlı)','Партнёрская кампания (необязательно)'])}><select value={draft.campaignId} disabled={draft.format==='story'} onChange={e=>update('campaignId',e.target.value)}><option value="">{tr(['پست عمومی — بدون افیلیت','General post — no affiliate flow','Genel gönderi — ortaklık yok','Обычная публикация — без партнёрства'])}</option>{campaigns.map(c=><option key={c.id} value={c.id} disabled={!c.data.active}>{c.data.name}</option>)}</select></Field>
   {draft.campaignId&&<p className="pub-note">{tr(['محتوای کمپین در batch سه‌تایی منتشر می‌شود؛ پست اسلایدی چهار رسانه با ترتیب TR/FA/EN/RU و کپشن ترکی دارد.','Campaign content publishes in batches of three. Carousels use four slides TR/FA/EN/RU and a Turkish caption.','Kampanya üçlü gruplarla yayınlanır. Kaydırmalı içerik TR/FA/EN/RU sıralı dört slayt ve Türkçe açıklama kullanır.','Кампании публикуются по три. Карусели: четыре слайда TR/FA/EN/RU и турецкая подпись.'])}</p>}
   <Field label={tr(['منطقه زمانی انتشار','Publishing time zone','Yayın saat dilimi','Часовой пояс публикации'])}><input dir="ltr" value={draft.timezone} onChange={e=>update('timezone',e.target.value)}/></Field>
  </section><section className="pub-card pub-editor-media"><div className="pub-card-top"><h2>{tr(['رسانه و اسلایدها','Media & slides','Medya ve slaytlar','Медиа и слайды'])}</h2><button className="pub-secondary" onClick={()=>setModal('library')}><FolderOpen size={14}/>{tr(['کتابخانه','Library','Kitaplık','Библиотека'])}</button></div>
   <div className="pub-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void uploadFiles(Array.from(e.dataTransfer.files));}}><Upload size={30}/><b>{tr(['فایل‌ها را اینجا رها کنید','Drop your media here','Dosyaları buraya bırakın','Перетащите файлы сюда'])}</b><span>JPEG / PNG · MP4 · {tr(['تصویر ۸MB، ویدئو ۳۰۰MB','Images 8MB, video 300MB','Görsel 8MB, video 300MB','Фото 8MB, видео 300MB'])}</span><button className="pub-secondary" onClick={()=>fileInput.current?.click()}>{tr(['انتخاب فایل','Choose files','Dosya seç','Выбрать файлы'])}</button><input ref={fileInput} data-post-upload type="file" hidden multiple={draft.format==='carousel'} accept="image/jpeg,image/png,video/mp4" onChange={e=>{void uploadFiles(Array.from(e.target.files||[]));e.target.value='';}}/></div>
   {!storage?.configured&&<p className="pub-note banner">{tr(['برای ماندگاری روی هاست، Volume واقعی و BAZINO_DATA_DIR لازم است.','Production persistence requires a real volume and BAZINO_DATA_DIR.','Kalıcılık için gerçek Volume ve BAZINO_DATA_DIR gerekir.','Для хранения нужен настоящий том и BAZINO_DATA_DIR.'])}</p>}
   {uploads.map(u=><div className="pub-upload-progress" key={u.id}><div><b>{u.name}</b><StateBadge value={u.status}/><span>{u.progress}%</span>{controllers.current.has(u.id)&&<button className="pub-icon-button" onClick={()=>controllers.current.get(u.id)?.abort()} aria-label={c('cancel')}>×</button>}{u.status==='failed'&&<button className="pub-secondary" onClick={()=>void uploadFiles([u.file],assets.find(a=>a.id===u.assetId&&a.data.status==='uploading'))}>{tr(['ادامه / تلاش دوباره','Resume / retry','Devam / tekrar','Продолжить / повторить'])}</button>}</div><progress max="100" value={u.progress}/>{u.error&&<code>{u.error}</code>}</div>)}
   <div className="pub-slide-grid">{draft.assetIds.map((id:string,index:number)=><div className="pub-slide" key={id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(index))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(from)&&from>=0&&from<draft.assetIds.length)move(from,index);}}><div className="pub-slide-thumb"><MediaPreview asset={asset(id)}/><b>{index+1}</b></div><small>{asset(id)?.data.name||id}</small><div><button className="pub-icon-button" disabled={index===0} onClick={()=>move(index,index-1)} aria-label={tr(['اسلاید قبلی','Move earlier','Öne taşı','Переместить раньше'])}><ArrowUp size={13}/></button><button className="pub-icon-button" disabled={index===draft.assetIds.length-1} onClick={()=>move(index,index+1)} aria-label={tr(['اسلاید بعدی','Move later','Sona taşı','Переместить позже'])}><ArrowDown size={13}/></button><button className="pub-icon-button" onClick={()=>update('assetIds',draft.assetIds.filter((x:string)=>x!==id))} aria-label={tr(['حذف اسلاید','Remove slide','Slaytı kaldır','Удалить слайд'])}><Trash2 size={13}/></button></div></div>)}</div>
   {draft.format==='reel'&&<Field label={tr(['کاور تصویر (اختیاری)','Image cover (optional)','Kapak görseli (isteğe bağlı)','Обложка (необязательно)'])}><select value={draft.coverId||''} onChange={e=>update('coverId',e.target.value)}><option value="">{c('none')}</option>{assets.filter(a=>a.data.status==='ready'&&a.data.mime.startsWith('image/')).map(a=><option key={a.id} value={a.id}>{a.data.name}</option>)}</select></Field>}
   <p className="pub-note">{tr(['ویدئو: MP4 با H.264/HEVC، ۳ تا ۹۰ ثانیه. تصاویر بدون برش خودکار برای preview آماده می‌شوند؛ اصل فایل محفوظ است.','Video: MP4 H.264/HEVC, 3–90 seconds. Images are prepared without automatic cropping; originals remain stored.','Video: MP4 H.264/HEVC, 3–90 saniye. Görseller kırpılmaz; asılları korunur.','Видео: MP4 H.264/HEVC, 3–90 секунд. Фото подготавливаются без обрезки; оригиналы сохраняются.'])}</p>
  </section></div>
  <div className="pub-editor-footer"><button className="pub-secondary" disabled={busy||!dirty} onClick={save} data-save-post><Save size={15}/>{tr(['ذخیره پیش‌نویس','Save draft','Taslağı kaydet','Сохранить черновик'])}</button><button className="pub-secondary" onClick={()=>{setSlide(0);setConfirmed(false);setModal('preview');}} disabled={!draft.assetIds.length}><Eye size={15}/>{tr(['پیش‌نمایش و تأیید','Preview & approve','Önizle ve onayla','Предпросмотр и одобрение'])}</button>{draft.status==='approved'&&!dirty&&!draft.campaignId&&<button className="pub-primary" disabled={busy||!can('publish')} onClick={()=>publicationDialog()}><Send size={15}/>{tr(['انتشار / زمان‌بندی','Publish / schedule','Yayınla / planla','Опубликовать / запланировать'])}</button>}{draft.status==='scheduled'&&<button className="pub-danger" disabled={busy} onClick={()=>action(async()=>{const r=await api('/publishing/drafts/'+editing.id+'/cancel','POST',{version:editing.version});setEditing(r);})}>{c('cancel')}</button>}</div>
 </>}
 {modal&&<PubModal title={modal==='library'?tr(['کتابخانهٔ خصوصی رسانه','Private media library','Özel medya kitaplığı','Личная медиатека']):modal==='generate'?tr(['درخواست از عامل','Agent task','Aracı görevi','Задание агенту']):tr(['بازبینی انتشار','Publication review','Yayın incelemesi','Проверка публикации'])} onClose={()=>setModal(null)}><ErrorNotice error={error}/>
  {modal==='library'&&<div className="pub-library-grid">{assets.filter(a=>a.data.status!=='cancelled').map(a=><article className="pub-library-item" key={a.id}><div className="pub-library-thumb"><MediaPreview asset={a}/></div><b>{a.data.name}</b><small>{a.data.width?`${a.data.width} × ${a.data.height}`:`${a.data.received} / ${a.data.size}`} · {(a.data.size/1048576).toFixed(1)} MB</small><StateBadge value={a.data.status}/><div className="pub-actions"><button className="pub-primary" disabled={a.data.status!=='ready'} onClick={()=>{selectAsset(a.id);setModal(null);}}>{tr(['استفاده','Use','Kullan','Использовать'])}</button><button className="pub-danger" onClick={()=>action(()=>api('/publishing/assets/'+a.id,'DELETE'))}><Trash2 size={13}/></button></div>{a.data.status==='uploading'&&<label className="pub-secondary">{tr(['ادامه با همان فایل','Resume with same file','Aynı dosyayla devam','Продолжить с тем же файлом'])}<input type="file" hidden accept="image/jpeg,image/png,video/mp4" onChange={e=>{if(e.target.files?.[0]){setModal(null);void uploadFiles([e.target.files[0]],a);}}}/></label>}</article>)}</div>}
  {modal==='preview'&&draft&&<><div className="pub-preview-frame"><header><b>BAZINO PRO</b><span>{label(draft.format)} · {draft.language.toUpperCase()}</span></header><div className="pub-preview-media"><MediaPreview asset={asset(draft.assetIds[slide])} large/></div>{draft.assetIds.length>1&&<div className="pub-preview-pagination"><button className="pub-secondary" disabled={slide===0} onClick={()=>setSlide(x=>x-1)}><ChevronLeft size={14}/></button><span>{slide+1} / {draft.assetIds.length}</span><button className="pub-secondary" disabled={slide===draft.assetIds.length-1} onClick={()=>setSlide(x=>x+1)}><ChevronRight size={14}/></button></div>}<p className="pub-preview-caption">{draft.caption||'—'}</p></div><p className="pub-note">{tr(['پیش‌نمایش قالب دقیق رسانه و ترتیب آن را نشان می‌دهد؛ ظاهر اپ اینستاگرام ممکن است متفاوت باشد.','Preview shows the exact media order; Instagram’s app appearance may differ.','Önizleme medya sırasını gösterir; Instagram görünümü farklı olabilir.','Предпросмотр показывает порядок медиа; вид Instagram может отличаться.'])}</p><Toggle label={tr(['همین رسانه‌ها، ترتیب، کپشن و مقصد را تأیید می‌کنم.','I approve these media, their order, the caption and destination.','Bu medya, sıra, açıklama ve hedefi onaylıyorum.','Одобряю эти медиа, порядок, подпись и назначение.'])} checked={confirmed} onChange={setConfirmed}/><button className="pub-primary" disabled={busy||dirty||!confirmed||draft.status!=='draft'||!can('publish')} data-approve-post onClick={()=>action(async()=>{const r=await api('/publishing/drafts/'+editing.id+'/approve','POST',{version:editing.version,confirmed:true});setEditing(r);setModal(null);})}><ShieldCheck size={15}/>{tr(['تأیید همین نسخه','Approve this version','Bu sürümü onayla','Одобрить эту версию'])}</button>{dirty&&<p className="pub-note">{tr(['ابتدا پیش‌نویس را ذخیره کنید.','Save the draft first.','Önce taslağı kaydedin.','Сначала сохраните черновик.'])}</p>}</>}
  {modal==='publish'&&<form onSubmit={e=>{e.preventDefault();void publish();}}>{batchPublish&&<div className="pub-batch-preview">{selected.map(id=>{const d=drafts.find(d=>d.id===id);return <section className="pub-card" key={id}><h3>{d?.data.title}</h3><div className="pub-slide-grid">{d?.data.assetIds.map((aid:string)=><div className="pub-library-thumb" key={aid}><MediaPreview asset={asset(aid)} large/></div>)}</div><p className="pub-preview-caption">{d?.data.caption}</p></section>;})}</div>}<p className="pub-note">{cfg.config.data.outboundEnabled?tr(['این اقدام کار انتشار واقعی را ایجاد می‌کند.','This creates a real publishing job.','Bu işlem gerçek yayın işi oluşturur.','Это создаёт реальное задание публикации.']):tr(['ارسال زنده خاموش است؛ کار در صف می‌ماند تا مدیر آن را فعال کند.','Live delivery is paused. The job remains queued until enabled.','Canlı gönderim kapalı; yönetici açana kadar iş kuyrukta kalır.','Отправка приостановлена: задание будет ждать включения.'])}</p><Toggle label={tr(['انتشار در اولین فرصت','Publish as soon as enabled','İlk fırsatta yayınla','Опубликовать при первой возможности'])} checked={publishNow} onChange={setPublishNow}/>{!publishNow&&<Field label={tr(['تاریخ و ساعت در منطقهٔ زمانی پست','Date/time in the post’s time zone','Gönderinin saat diliminde tarih/saat','Дата/время в часовом поясе публикации'])}><input type="datetime-local" required value={when} onChange={e=>setWhen(e.target.value)}/><small>{draft?.timezone||cfg.config.data.timezone}</small></Field>}<Toggle label={tr(['انتشار نسخه‌های نمایش‌داده‌شده را تأیید می‌کنم.','I confirm publishing the shown versions.','Gösterilen sürümlerin yayınını onaylıyorum.','Подтверждаю публикацию показанных версий.'])} checked={confirmed} onChange={setConfirmed}/>{(draft?.executionMode==='agent'||batchPublish&&drafts.some(d=>selected.includes(d.id)&&d.data.executionMode==='agent'))&&<Toggle label={tr(['مصرف اعتبار عامل برای این کار مصوب را تأیید می‌کنم.','I authorize agent credit usage for this approved job.','Onaylı iş için aracı kredisi kullanımını onaylıyorum.','Разрешаю расход кредитов агента для одобренного задания.'])} checked={agentCost} onChange={setAgentCost}/>}<button className="pub-primary" disabled={busy||!confirmed} data-confirm-publish>{tr(['ثبت کار انتشار','Queue publication','Yayın işini kaydet','Поставить публикацию в очередь'])}</button></form>}
  {modal==='generate'&&<form onSubmit={e=>{e.preventDefault();void action(async()=>{await api('/publishing/drafts/'+editing.id+'/generate','POST',{agentId:draft.agentId,brief,confirmedCost:confirmed});setModal(null);});}}><Field label={tr(['شرح کار؛ فقط پیش‌نویس کپشن','Brief — caption draft only','Talimat — yalnızca açıklama taslağı','Задание — только черновик подписи'])}><textarea rows={5} value={brief} onChange={e=>setBrief(e.target.value)} required maxLength={5000}/></Field><Toggle label={tr(['ارسال درخواست به عامل و مصرف احتمالی اعتبار را تأیید می‌کنم؛ این کار انتشار نیست.','I authorize this agent request and possible credits. This does not publish.','Aracı isteği ve olası kredi kullanımını onaylıyorum; bu yayın değildir.','Разрешаю запрос агенту и возможные расходы; это не публикация.'])} checked={confirmed} onChange={setConfirmed}/><button className="pub-primary" disabled={!confirmed||busy}>{tr(['ارسال درخواست','Send request','İsteği gönder','Отправить запрос'])}</button></form>}
 </PubModal>}
 </div>;
}
