import React,{useState,useEffect,useCallback} from 'react';
import {Send,Layers,ShieldCheck,Bot,Settings2,Activity,ImagePlus,ArrowUpRight,RefreshCw,Plus,Hand,Sparkles,Link2,KeyRound,Users,Eye,Clock,ChevronRight,Copy,MessageCircle,Inbox} from 'lucide-react';
import {PostManager} from './PostManager';
import {TelegramTab} from './Telegram';
import {IgInboxTab} from './IgInbox';
import {LegacyContentConsole} from '../management/LegacyContent';
import {CAMPAIGN_MESSAGES} from './messages';
import {useCopy,COPY,Field,Toggle,PubModal,StateBadge,ErrorNotice} from './ui';
import './studio.css';

type Tab='overview'|'posts'|'campaigns'|'media'|'agents'|'settings'|'events'|'telegram'|'inbox'|'legacy';
export function PublishingStudio({initialTab='overview'}:{initialTab?:Tab}){
 const {api,c,tr,staff,language,can}=useCopy();
 const [period,setPeriod]=useState(''),[settlement,setSettlement]=useState<any>(null);
 const [tab,setTab]=useState<Tab>(initialTab),[cfg,setCfg]=useState<any>(null),[agents,setAgents]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[media,setMedia]=useState<any[]>([]),[events,setEvents]=useState<any>(null),[report,setReport]=useState<any>(null),[members,setMembers]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[modal,setModal]=useState<any>(null);
 const admin=!!staff?.admin,canReport=can('reports');
 const reload=useCallback(async()=>{
  try{
   const [a,b,cs,m]=await Promise.all([api('/publishing/config'),api('/publishing/agents'),api('/publishing/campaigns'),api('/publishing/media')]);setCfg(a);setAgents(b);setCampaigns(cs);setMedia(m);
   if(canReport){setEvents(await api('/publishing/events'));setReport(await api('/publishing/reports'));}
   if(admin)setMembers(await api('/publishing/members'));
  }catch(e:any){setError(e.code||e.message);}
 },[api,admin,canReport]);
 useEffect(()=>{void reload();},[reload]);
 async function act(fn:()=>Promise<any>,close=true){setBusy(true);setError('');setSaved(false);try{await fn();if(close)setModal(null);await reload();setSaved(true);return true;}catch(e:any){setError(e.code||e.message||'OPERATION_FAILED');return false;}finally{setBusy(false);}}
 const mode=cfg?.config?.data.selectedMode;
 const totals=(key:string)=>(report?.campaigns||[]).reduce((n:number,r:any)=>n+Number(r[key]||0),0);
 const count=(n:number)=>new Intl.NumberFormat(language==='fa'?'fa-IR':language).format(n||0);
 const tabs:Array<[Tab,any]>= [['overview',Layers],['posts',Send],['campaigns',Users],['media',ImagePlus],['events',Activity],...(admin?[['agents',Bot],['settings',Settings2],['telegram',MessageCircle],['inbox',Inbox]]:[]) as any,['legacy',Clock]];
 return <section className="pub-app" dir={language==='fa'?'rtl':'ltr'} data-publishing-studio>
  <header className="pub-heading"><div><span className="pub-eyebrow">BAZINO · CONTENT STUDIO</span><h1>{c('title')} <span className="pub-version">V4</span></h1><p>{tr(['از محتوای مصوب تا انتشار و دعوت دوست؛ یک جریان قابل پیگیری.','From approved content to publication and friend invitations.','Onaylı içerikten yayına ve arkadaş davetine.','От одобренного контента до публикации и приглашений.'])}</p></div><button className="pub-secondary" onClick={()=>reload()} aria-label={c('refresh')}><RefreshCw size={15}/><span>{c('refresh')}</span></button></header>
  <div className="pub-control-bar"><div className="pub-mode" aria-label={tr(['حالت انتشار','Publishing mode','Yayın modu','Режим публикации'])}>{(['manual','agent'] as const).map(m=><button key={m} type="button" data-publishing-mode={m} className={mode===m?'selected':''} disabled={!admin||busy||!cfg} onClick={()=>act(()=>api('/publishing/config','PUT',{...cfg.config.data,selectedMode:m,version:cfg.config.version}),false)}>{m==='manual'?<Hand size={15}/>:<Sparkles size={15}/>} {c(m)}</button>)}</div>
   <div className="pub-delivery"><i className={cfg?.config?.data.outboundEnabled?'on':''}/>{cfg?.config?.data.outboundEnabled?tr(['ارسال واقعی فعال','Live delivery enabled','Canlı gönderim açık','Реальная отправка включена']):tr(['ارسال واقعی خاموش','Live delivery paused','Canlı gönderim kapalı','Реальная отправка приостановлена'])}</div>
   <span className="pub-default-agent"><Bot size={14}/>{tr(['عامل پیش‌فرض','Default agent','Varsayılan aracı','Агент по умолчанию'])}: {agents.find(a=>a.id===cfg?.config.data.defaultAgentId)?.data.name||c('none')}</span>
  </div>
  <nav className="pub-tabs">{tabs.map(([key,Icon])=><button key={key} type="button" data-pub-tab={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setError('');setSaved(false);}}><Icon size={16}/>{c(key)}</button>)}</nav>
  <ErrorNotice error={error}/>{saved&&!modal&&<p role="status" className="pub-success">{tr(['تغییرات در سرور ذخیره شد.','Changes saved on the server.','Değişiklikler sunucuya kaydedildi.','Изменения сохранены на сервере.'])}</p>}
  {!cfg?<div className="pub-empty">{c('loading')}</div>:<>
  {tab==='overview'&&<>
   <div className="pub-stat-grid">{[
    [tr(['رسانهٔ مجاز','Approved media','Onaylı medya','Разрешённые медиа']),media.filter(m=>m.data.active).length,ImagePlus],
    [tr(['همکاران کمپین','Campaign partners','Kampanya ortakları','Участники кампании']),totals('partners'),Users],
    [tr(['دعوت‌های فعال','Activated invitations','Etkin davetler','Активированные приглашения']),totals('leads'),ShieldCheck],
    [tr(['پیام در صف','Messages queued','Kuyruktaki mesajlar','Сообщения в очереди']),events?.counts?.queued||0,Clock],
   ].map(([label,n,Icon]:any,i)=><div className="pub-stat" key={i}><div><span>{label}</span><strong>{count(n)}</strong></div><Icon size={23}/></div>)}</div>
   <div className="pub-overview-grid"><section className="pub-card"><div className="pub-card-top"><h2>{tr(['مسیر انتشار','Publishing flow','Yayın akışı','Путь публикации'])}</h2><ShieldCheck size={18}/></div><div className="pub-flow">{[
    tr(['آماده‌سازی محتوا','Prepare content','İçeriği hazırla','Подготовка']),tr(['پیش‌نمایش و تأیید','Preview & approve','Önizle ve onayla','Предпросмотр']),tr(['انتشار و ثبت رسانه','Publish & register','Yayınla ve kaydet','Публикация']),tr(['دعوت و انتساب','Invite & attribute','Davet ve ilişkilendir','Приглашение']),
   ].map((s,i)=><div key={s}><b>{String(i+1).padStart(2,'0')}</b><span>{s}</span>{i<3&&<ChevronRight size={14}/>}</div>)}</div><p className="pub-note">{tr(['عامل فقط شناسهٔ رسانهٔ منتشرشده را اعلام می‌کند. کد همکار، لینک دوست و کوپن در بک‌اند مدیریت می‌شوند.','The agent reports the published media ID. Partner codes, friend links and coupons remain server-owned.','Aracı yayımlanan medya ID’sini bildirir. Kod, bağlantı ve kuponları sunucu yönetir.','Агент сообщает ID медиа. Коды, ссылки и купоны управляются сервером.'])}</p></section>
   <section className="pub-card pub-endpoint"><span className="pub-eyebrow">WEBHOOK RECEIVER</span><h2>Zernio</h2><code dir="ltr">{cfg.webhookUrl}</code><button className="pub-secondary" onClick={()=>navigator.clipboard?.writeText(cfg.webhookUrl)}><Copy size={14}/>{tr(['کپی نشانی','Copy URL','Adresi kopyala','Копировать URL'])}</button><p className="pub-note">{tr(['اشتراک سمت Zernio و سلامت گیرنده جدا هستند؛ هیچ نتیجهٔ شبیه‌ساز، ارسال زنده نیست.','A subscription is not proof of delivery. Simulated results are never live sends.','Abonelik teslim kanıtı değildir. Simülasyon canlı gönderim değildir.','Подписка не доказывает доставку. Симуляция — не реальная отправка.'])}</p></section></div>
   <section className="pub-card"><div className="pub-card-top"><h2>{tr(['عملکرد کمپین‌ها','Campaign performance','Kampanya performansı','Результаты кампаний'])}</h2><span className="pub-muted">{tr(['دادهٔ مرجع سرور','Server records','Sunucu kayıtları','Данные сервера'])}</span></div><div className="pub-table-scroll"><table><thead><tr>{[c('campaigns'),tr(['کلیک','Clicks','Tıklamalar','Клики']),tr(['رزرو','Reserved','Rezervasyon','Брони']),tr(['پرداخت','Paid','Ödenen','Оплачено']),tr(['فروش خالص','Net sales','Net satış','Чистые продажи']),tr(['کمیسیون معلق','Pending commission','Bekleyen komisyon','Ожидающая комиссия'])].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{(report?.campaigns||[]).map((r:any)=><tr key={r.id}><td><b>{r.name}</b></td><td>{count(r.clicks)}</td><td>{count(r.reserved)}</td><td>{count(r.paid)}</td><td>{count(r.netSales)} TL</td><td>{count(r.pending)} TL</td></tr>)}</tbody></table></div></section>
  </>}
  {tab==='overview'&&admin&&<section className="pub-card"><h2>{tr(['تسویهٔ ماهانهٔ کمیسیون','Monthly commission settlement','Aylık komisyon mutabakatı','Месячный расчёт комиссий'])}</h2><p className="pub-note">{tr(['فقط کمیسیون‌های مصوبِ ماه بسته‌شده به کیف پول واریز می‌شوند. این عمل تحویل نقد نیست.','Only approved commissions from a closed month are credited to wallets. This is not a cash handover.','Yalnızca kapanmış ayın onaylı komisyonları cüzdana yatırılır. Bu nakit teslimi değildir.','Только одобренные комиссии закрытого месяца зачисляются в кошелёк. Это не выдача наличных.'])}</p><div className="pub-actions"><Field label={tr(['ماه (UTC)','Month (UTC)','Ay (UTC)','Месяц (UTC)'])}><input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></Field><button className="pub-secondary" disabled={!period||busy} onClick={()=>{if(confirm(tr(['واریز کمیسیون‌های مصوب این ماه به کیف پول انجام شود؟','Credit approved commissions for this month to wallets?','Bu ayın onaylı komisyonları cüzdana yatırılsın mı?','Зачислить одобренные комиссии месяца в кошельки?'])))void act(async()=>setSettlement(await api('/publishing/settlements','POST',{period,confirmed:true})),false);}}>{tr(['واریز به کیف پول','Credit wallets','Cüzdana yatır','Зачислить в кошельки'])}</button></div>{settlement&&<p className="pub-success">{tr(['واریز شد','Credited','Yatırıldı','Зачислено'])}: {count(settlement.credited)} TL · {tr(['موارد نیازمند رسیدگی','Items requiring review','İnceleme gerekenler','Требуют проверки'])}: {settlement.skipped.length}</p>}</section>}
  {tab==='posts'&&<PostManager cfg={cfg} agents={agents} campaigns={campaigns} onRefresh={reload}/>}
  {tab==='campaigns'&&<><div className="pub-section-title"><h2>{c('campaigns')}</h2>{admin&&<button className="pub-primary" onClick={()=>setModal({type:'campaign',id:'',version:0,data:{...campaigns[0]?.data,name:'',active:false,financialApproved:false,couponEnabled:false,messages:structuredClone(CAMPAIGN_MESSAGES)}})}><Plus size={16}/>{c('add')}</button>}</div><div className="pub-card-grid">{campaigns.map(r=><div className="pub-card" key={r.id}><div className="pub-card-top"><span className="pub-eyebrow">{r.id}</span><StateBadge value={r.data.active?'approved':'disabled'}/></div><h2>{r.data.name}</h2><div className="pub-language-tags">{r.data.languages.map((l:string)=><span key={l}>{l.toUpperCase()} <b>{r.data.keywords[l]}</b></span>)}</div><p className="pub-note">{r.data.requireVerifiedFollow?tr(['فقط سیگنال رسمی Follow','Verified follow signal required','Doğrulanmış takip gerekli','Требуется проверенная подписка']):tr(['دکمهٔ Follow با برچسب خوداظهاری','Follow button with self-declaration label','Takip düğmesi, beyan etiketiyle','Кнопка подписки с пометкой заявления'])}</p><div className="pub-card-bottom"><small>{c('version')} {r.version} · {r.data.financialApproved?tr(['سیاست مالی مصوب','Financial policy approved','Mali politika onaylı','Финансовая политика одобрена']):tr(['مالی در انتظار تأیید','Financial approval pending','Mali onay bekliyor','Финансовое одобрение ожидается'])}</small>{admin&&<button className="pub-secondary" onClick={()=>setModal({type:'campaign',...structuredClone(r)})}>{c('edit')}</button>}</div></div>)}</div>
   <section className="pub-card"><h2>{tr(['شرکت‌کنندگان','Participants','Katılımcılar','Участники'])}</h2><div className="pub-table-scroll"><table><thead><tr>{[c('name'),tr(['نقش','Role','Rol','Роль']),tr(['کد','Code','Kod','Код']),c('status'),tr(['روش اثبات','Evidence','Kanıt','Свидетельство'])].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{members.map(m=><tr key={m.id}><td>{m.username}</td><td>{m.role==='partner'?tr(['همکار','Partner','Ortak','Партнёр']):tr(['دوست','Friend','Arkadaş','Друг'])}</td><td dir="ltr">{m.partnerCode}</td><td><StateBadge value={m.status}/></td><td><small>{m.followMethod||m.shareStatus||'—'}</small></td></tr>)}</tbody></table>{!members.length&&<div className="pub-empty small">{c('empty')}</div>}</div></section>
  </>}
  {tab==='media'&&<><div className="pub-section-title"><h2>{c('media')}</h2>{admin&&<button className="pub-primary" onClick={()=>setModal({type:'register',nativeId:'',campaignId:cfg.config.data.defaultCampaignId,mediaType:'post'})}><Plus size={16}/>{tr(['ثبت شناسهٔ رسانه','Register media ID','Medya ID kaydet','Зарегистрировать медиа'])}</button>}</div><div className="pub-note banner">{tr(['کشف پست توسط Zernio به‌تنهایی اجازهٔ افیلیت نیست؛ رسانه و کمپین باید تأیید شوند.','Discovery alone never enables affiliate processing. The media and campaign must be approved.','Keşif tek başına ortaklık izni değildir. Medya ve kampanya onaylanmalıdır.','Обнаружение публикации не разрешает партнёрскую обработку. Нужны одобрения.'])}</div><section className="pub-card"><div className="pub-table-scroll"><table><thead><tr>{['Instagram Media ID',tr(['منشأ','Source','Kaynak','Источник']),c('campaigns'),c('status'),''].map((s,i)=><th key={i}>{s}</th>)}</tr></thead><tbody>{media.map(r=><tr key={r.id}><td dir="ltr"><code>{r.data.nativeId}</code><small className="pub-block">{r.data.mediaType}</small></td><td>{r.data.source}</td><td>{r.data.campaignId||'—'}</td><td><StateBadge value={r.data.active?'approved':r.data.approval}/></td><td>{admin&&<button className="pub-secondary" onClick={()=>setModal({type:'media',...structuredClone(r)})}>{c('edit')}</button>}</td></tr>)}</tbody></table>{!media.length&&<div className="pub-empty">{c('empty')}</div>}</div></section></>}
  {tab==='agents'&&admin&&<><div className="pub-section-title"><h2>{c('agents')}</h2><button className="pub-primary" onClick={()=>setModal({type:'agent',version:0,data:{name:'',adapterId:'manus',enabled:true,projectId:'',profile:'standard'}})}><Plus size={16}/>{c('add')}</button></div><div className="pub-note banner">{tr(['API Key سرویس عامل با توکن baz_ سایت متفاوت است. تعریف عامل یا انتخاب حالت، هیچ انتشار یا مصرف اعتباری ایجاد نمی‌کند.','An agent API key is different from a baz_ ingest token. Creating an agent or choosing a mode does not publish or spend credits.','Aracı API anahtarı baz_ tokeninden farklıdır. Aracı oluşturmak veya mod seçmek yayın/kredi harcaması yapmaz.','API-ключ агента отличается от токена baz_. Создание агента или выбор режима не публикует и не расходует кредиты.'])}</div><div className="pub-card-grid">{agents.map(a=><section className="pub-card pub-agent" key={a.id} data-agent-card={a.id}><div className="pub-card-top"><div className="pub-avatar"><Bot size={23}/></div>{a.id===cfg.config.data.defaultAgentId&&<span className="pub-badge good">{c('default')}</span>}</div><h2>{a.data.name}</h2><p className="pub-muted">{a.data.adapterId} · {a.data.profile}</p><StateBadge value={a.status}/><p className="pub-muted">{tr(['منبع کلید','Credential source','Anahtar kaynağı','Источник ключа'])}: {a.source==='host'?tr(['هاست','Host','Sunucu','Хост']):a.source==='legacy'?tr(['تنظیم قبلی','Legacy setting','Önceki ayar','Прежняя настройка']):tr(['پنل','Panel','Panel','Панель'])}</p><p className="pub-note">{tr(['فقط وضعیت کلید نمایش داده می‌شود؛ مقدار ذخیره‌شده به مرورگر برنمی‌گردد.','Only credential status is shown. The saved key is not returned to the browser.','Yalnızca anahtar durumu gösterilir. Kayıtlı anahtar tarayıcıya dönmez.','Показывается только статус. Сохранённый ключ не возвращается в браузер.'])}</p><div className="pub-actions"><button className="pub-secondary" onClick={()=>setModal({type:'agent',...structuredClone(a)})}>{c('edit')}</button><button className="pub-secondary" disabled={!a.configured||!a.data.enabled||busy||a.data.adapterId!=='manus'} onClick={()=>{if(confirm(tr(['تست خواندنی اتصال به سرویس انجام شود؟','Run a read-only connection check?','Salt okunur bağlantı testi yapılsın mı?','Выполнить проверку подключения без записи?'])))void act(()=>api('/publishing/agents/'+a.id+'/test','POST',{confirmed:true}),false);}}>{tr(['تست اتصال','Test connection','Bağlantı testi','Проверить связь'])}</button>{a.id!==cfg.config.data.defaultAgentId&&<button className="pub-secondary" disabled={!a.data.enabled||busy} onClick={()=>act(()=>api('/publishing/config','PUT',{...cfg.config.data,defaultAgentId:a.id,version:cfg.config.version}),false)}>{c('default')}</button>}</div></section>)}</div></>}
  {tab==='settings'&&admin&&<SettingsPane cfg={cfg} agents={agents} campaigns={campaigns} busy={busy} act={act} setModal={setModal}/>}
  {tab==='events'&&<><div className="pub-section-title"><h2>{c('events')}</h2><span className="pub-muted">{tr(['بدون بدنهٔ خصوصی و سکرت','No private payloads or credentials','Özel yük/anahtar gösterilmez','Без личных данных и ключей'])}</span></div>{[['inbox',tr(['دریافت‌ها','Inbox','Gelen olaylar','Входящие'])],['outbox',tr(['ارسال‌ها','Outbox','Giden olaylar','Исходящие'])]].map(([key,title])=><section className="pub-card" key={key}><h2>{title}</h2><div className="pub-table-scroll"><table><thead><tr><th>{tr(['رویداد','Event','Olay','Событие'])}</th><th>{c('status')}</th><th>{tr(['زمان','Time','Zaman','Время'])}</th><th>{tr(['خطا / رسیدگی','Error / review','Hata / inceleme','Ошибка / проверка'])}</th></tr></thead><tbody>{(events?.[key]||[]).map((e:any)=><tr key={e.id}><td dir="ltr">{e.type||e.stage}</td><td><StateBadge value={e.status}/></td><td>{e.at?new Date(e.at).toLocaleString(language):'—'}</td><td><code>{e.error||'—'}</code>{e.evidence==='operator_confirmed'&&<small className="pub-block">{tr(['تأیید اپراتور، نه رسید خودکار','Operator confirmation, not an automatic receipt','Operatör onayı; otomatik makbuz değil','Подтверждение оператора, не автоквитанция'])}</small>}{key==='outbox'&&admin&&e.status==='failed'&&<button className="pub-secondary" disabled={busy} onClick={()=>{if(confirm(tr(['پس از رفع علت، درخواست قطعاً ناموفق دوباره ارسال شود؟','Retry this definitively failed request after fixing its cause?','Nedeni giderdikten sonra başarısız istek tekrarlansın mı?','Повторить явно неудачную попытку после исправления причины?'])))void act(()=>api('/publishing/outbox/'+e.id+'/retry','POST',{confirmed:true}),false);}}>{tr(['تلاش مجدد','Retry','Tekrar dene','Повторить'])}</button>}{key==='outbox'&&admin&&e.status==='delivery_unknown'&&<button className="pub-secondary" onClick={()=>setModal({type:'outbox',id:e.id})}>{tr(['ثبت مشاهدهٔ پیام','Record observed message','Gözlenen mesajı kaydet','Записать найденное сообщение'])}</button>}</td></tr>)}</tbody></table>{!events?.[key]?.length&&<div className="pub-empty small">{c('empty')}</div>}</div></section>)}</>}
  {tab==='telegram'&&admin&&<TelegramTab/>}
  {tab==='inbox'&&admin&&<IgInboxTab/>}
  {tab==='legacy'&&<LegacyContentConsole/>}
  </>}
  {modal&&<PubModal title={modal.type==='campaign'?c('campaigns'):modal.type==='agent'?c('agents'):modal.type==='secret'?tr(['ثبت امن کلید','Secure credential','Güvenli anahtar','Безопасное сохранение ключа']):c('media')} onClose={()=>{setModal(null);setError('');}}><ErrorNotice error={error}/>
   {modal.type==='outbox'&&<OutboxResolveForm busy={busy} save={b=>act(()=>api('/publishing/outbox/'+modal.id+'/confirm-observed','POST',b))}/>}
   {modal.type==='campaign'&&<CampaignForm initial={modal} busy={busy} save={b=>act(()=>api('/publishing/campaigns/'+b.id,'PUT',{...b.data,version:b.version,policyConfirmed:b.confirmed}))}/>}
   {modal.type==='agent'&&<AgentForm initial={modal} busy={busy} vault={cfg?.vaultAvailable} save={b=>act(()=>api('/publishing/agents'+(b.id?'/'+b.id:''),b.id?'PUT':'POST',{...b.data,version:b.version,...(b.clearKey?{apiKey:''}:b.apiKey?{apiKey:b.apiKey}:{})}))}/>}
   {modal.type==='secret'&&<SecretForm busy={busy} name={modal.key} configured={cfg?.secrets?.[modal.key]?.configured} save={value=>act(()=>api('/publishing/secrets/'+modal.key,'PUT',{value}))}/>}
   {['media','register'].includes(modal.type)&&<MediaForm initial={modal} campaigns={campaigns} busy={busy} save={b=>act(()=>b.type==='register'?api('/publishing/media','POST',{media_id:b.nativeId,media_type:b.mediaType,campaign_id:b.campaignId}):api('/publishing/media/'+b.id,'PUT',{...b.data,version:b.version}))}/>}
  </PubModal>}
 </section>;
}
function SettingsPane({cfg,agents,campaigns,busy,act,setModal}:any){
 const {api,c,tr}=useCopy();const [edit,setEdit]=useState<any>(cfg.config.data);useEffect(()=>setEdit(cfg.config.data),[cfg.config.version]);
 return <><section className="pub-card"><h2>{tr(['اتصال و کنترل ارسال','Connection & delivery controls','Bağlantı ve gönderim','Подключение и отправка'])}</h2><form onSubmit={e=>{e.preventDefault();void act(()=>api('/publishing/config','PUT',{...edit,version:cfg.config.version}),false);}}><div className="pub-form-grid">
 <Field label="Zernio Instagram Account ID"><input dir="ltr" disabled={cfg.accountFromHost} value={edit.zernioAccountId} onChange={e=>setEdit({...edit,zernioAccountId:e.target.value})}/></Field><Field label={tr(['نشانی اصلی سایت','Public site URL','Site adresi','Адрес сайта'])}><input dir="ltr" type="url" required value={edit.baseUrl} onChange={e=>setEdit({...edit,baseUrl:e.target.value})}/></Field>
 <Field label={tr(['منطقه زمانی','Time zone','Saat dilimi','Часовой пояс'])}><input dir="ltr" required value={edit.timezone} onChange={e=>setEdit({...edit,timezone:e.target.value})}/></Field><Field label={tr(['کمپین پیش‌فرض ورودی','Default ingest campaign','Varsayılan kampanya','Кампания по умолчанию'])}><select value={edit.defaultCampaignId} onChange={e=>setEdit({...edit,defaultCampaignId:e.target.value})}>{campaigns.map((r:any)=><option key={r.id} value={r.id}>{r.data.name}</option>)}</select></Field>
 </div><div className="pub-safety"><ShieldCheck size={18}/><div><Toggle label={tr(['ارسال واقعی فقط به حساب و رسانه‌های مصوب فعال شود','Enable live delivery to approved accounts and media','Onaylı hesap/medyaya canlı gönderimi aç','Включить реальную отправку для одобренных аккаунтов и медиа'])} checked={edit.outboundEnabled} onChange={v=>setEdit({...edit,outboundEnabled:v})}/><p>{tr(['قبل از فعال‌سازی، کلیدها، گیرنده و صف کارهای معلق را بررسی کنید.','Review credentials, the receiver and pending jobs before enabling.','Açmadan önce anahtarları, alıcıyı ve bekleyen işleri kontrol edin.','Перед включением проверьте ключи, приёмник и ожидающие задания.'])}</p></div></div><button disabled={busy} className="pub-primary">{c('save')}</button></form></section>
 <section className="pub-card"><h2>{tr(['سکرت‌های سمت سرور','Server-side credentials','Sunucu anahtarları','Серверные ключи'])}</h2>{!cfg.vaultAvailable&&<p className="pub-note banner">{tr(['برای ذخیره از پنل، BAZINO_SECRETS_KEY را روی هاست تنظیم کنید. مقادیر موجود هاست مستقل باقی می‌مانند.','Set BAZINO_SECRETS_KEY on the host to save credentials from the panel. Existing host credentials remain independent.','Panelden kayıt için BAZINO_SECRETS_KEY ayarlayın. Mevcut sunucu anahtarları bağımsızdır.','Для сохранения задайте BAZINO_SECRETS_KEY на хосте. Существующие ключи хоста независимы.'])}</p>}{['zernio_api_key','zernio_webhook_secret','zernio_analytics_webhook_secret'].map(key=><div className="pub-secret-row" key={key}><KeyRound size={17}/><div><code>{key.toUpperCase()}</code><small>{cfg.secrets[key]?.source==='host'?tr(['منبع: هاست','Source: host','Kaynak: sunucu','Источник: хост']):tr(['منبع: پنل/تنظیمات موجود','Source: panel/legacy','Kaynak: panel/mevcut','Источник: панель/прежний'])}</small></div><StateBadge value={cfg.secrets[key]?.configured?'stored':'unconfigured'}/><button className="pub-secondary" disabled={cfg.secrets[key]?.source==='host'||!cfg.vaultAvailable} onClick={()=>setModal({type:'secret',key})}>{c('edit')}</button></div>)}</section></>;
}
function AgentForm({initial,busy,vault,save}:any){const {c,tr}=useCopy();const [v,setV]=useState({...initial,apiKey:'',clearKey:false});const field=(k:string,val:any)=>setV({...v,data:{...v.data,[k]:val}});return <form onSubmit={e=>{e.preventDefault();void save(v);}}><div className="pub-form-grid"><Field label={c('name')}><input required value={v.data.name} onChange={e=>field('name',e.target.value)}/></Field><Field label={tr(['نوع آداپتور','Adapter type','Adaptör türü','Тип адаптера'])}><select value={v.data.adapterId} disabled={v.id==='builtin-manus'} onChange={e=>field('adapterId',e.target.value)}><option value="manus">Manus API v2</option><option value="unsupported">{tr(['عامل دیگر — نیازمند آداپتور','Other agent — adapter required','Diğer — adaptör gerekli','Другой — нужен адаптер'])}</option></select></Field><Field label="Project ID"><input dir="ltr" value={v.data.projectId} onChange={e=>field('projectId',e.target.value)}/></Field><Field label={tr(['پروفایل عامل','Agent profile','Aracı profili','Профиль агента'])}><input dir="ltr" value={v.data.profile} onChange={e=>field('profile',e.target.value)}/></Field></div><Field label="API Key" hint={tr(['خالی = بدون تغییر؛ توکن baz_ سایت را اینجا وارد نکنید.','Empty = unchanged. Do not enter a baz_ ingest token here.','Boş = değişmez. Buraya baz_ tokeni girmeyin.','Пусто = без изменений. Не вводите токен baz_.'])}><input type="password" autoComplete="new-password" value={v.apiKey} disabled={v.clearKey} onChange={e=>setV({...v,apiKey:e.target.value})} data-agent-api-key/></Field><Toggle label={tr(['کلید ذخیره‌شده صریحاً پاک شود','Explicitly clear stored credential','Kayıtlı anahtarı temizle','Удалить сохранённый ключ'])} checked={v.clearKey} onChange={clearKey=>setV({...v,clearKey,apiKey:''})}/><Toggle label={c('enabled')} checked={v.data.enabled} onChange={x=>field('enabled',x)}/><p className="pub-note">{tr(['ذخیره عامل، اتصال یا اجازهٔ انتشار واقعی نیست.','Saving an agent does not test it or authorize live publishing.','Aracı kaydı bağlantı testi veya yayın izni değildir.','Сохранение агента не проверяет подключение и не разрешает публикацию.'])}</p>{!vault&&v.apiKey&&<ErrorNotice error="SECRETS_KEY_REQUIRED"/>}<button className="pub-primary" disabled={busy||!!v.apiKey&&!vault}>{c('save')}</button></form>;}
function SecretForm({name,configured,busy,save}:any){const {c,tr}=useCopy();const [value,setValue]=useState('');return <form onSubmit={e=>{e.preventDefault();void save(value);}}><Field label={name.toUpperCase()} hint={tr(['مقدار فقط به سرور فرستاده و رمزگذاری می‌شود.','The value is sent only to the server and encrypted.','Değer yalnızca sunucuya gönderilir ve şifrelenir.','Значение отправляется только серверу и шифруется.'])}><input type="password" autoComplete="new-password" value={value} onChange={e=>setValue(e.target.value)} required/></Field><div className="pub-actions"><button className="pub-primary" disabled={busy||!value}>{c('save')}</button>{configured&&<button className="pub-danger" type="button" disabled={busy} onClick={()=>{if(confirm(tr(['کلید پاک شود؟','Clear the credential?','Anahtar temizlensin mi?','Удалить ключ?'])))void save('');}}>{tr(['پاک کردن کلید','Clear credential','Anahtarı sil','Удалить ключ'])}</button>}</div></form>;}
function MediaForm({initial,campaigns,busy,save}:any){const {c,tr}=useCopy();const [v,setV]=useState(initial);const d=v.type==='register'?v:v.data;const change=(key:string,val:any)=>setV(v.type==='register'?{...v,[key]:val}:{...v,data:{...v.data,[key]:val}});return <form onSubmit={e=>{e.preventDefault();void save(v);}}>{v.type==='register'&&<Field label="Instagram Media ID"><input dir="ltr" pattern="[0-9]+" required value={d.nativeId} onChange={e=>change('nativeId',e.target.value)}/></Field>}<Field label={c('campaigns')}><select value={d.campaignId} onChange={e=>change('campaignId',e.target.value)}><option value="">{c('none')}</option>{campaigns.map((r:any)=><option key={r.id} value={r.id}>{r.data.name}</option>)}</select></Field><Field label={tr(['نوع رسانه','Media type','Medya türü','Тип медиа'])}><select value={d.mediaType} onChange={e=>change('mediaType',e.target.value)}><option value="post">Post / Carousel</option><option value="reel">Reel</option><option value="unknown">{tr(['نامشخص','Unknown','Bilinmiyor','Неизвестно'])}</option></select></Field>{v.type!=='register'&&<><div className="pub-actions">{['tr','fa','en','ru'].map(l=><Toggle key={l} label={l.toUpperCase()} checked={d.languages?.includes(l)} onChange={checked=>change('languages',checked?[...(d.languages||[]),l]:d.languages.filter((x:string)=>x!==l))}/>)}</div><Toggle label={tr(['رسانه برای کمپین تأیید و فعال شود','Approve and activate for this campaign','Kampanya için onayla ve etkinleştir','Одобрить и активировать для кампании'])} checked={d.active} onChange={x=>change('active',x)}/></>}<button className="pub-primary" disabled={busy}>{c('save')}</button></form>;}
function CampaignForm({initial,busy,save}:any){
 const {c,tr}=useCopy();const [v,setV]=useState({...initial,confirmed:false}),[lang,setLang]=useState('fa');const d=v.data;const change=(k:string,val:any)=>setV({...v,data:{...d,[k]:val}});
 return <form onSubmit={e=>{e.preventDefault();void save(v);}}><div className="pub-form-grid"><Field label="Campaign ID"><input required dir="ltr" disabled={!!initial.id} pattern="[A-Za-z0-9_-]+" value={v.id} onChange={e=>setV({...v,id:e.target.value})}/></Field><Field label={c('name')}><input required value={d.name} onChange={e=>change('name',e.target.value)}/></Field><Field label="Zernio Account ID"><input dir="ltr" value={d.accountId||''} onChange={e=>change('accountId',e.target.value)}/></Field><Field label={tr(['حداقل سفارش کوپن (TL)','Coupon minimum order (TL)','Kupon minimum sipariş (TL)','Минимум для купона (TL)'])}><input type="number" min="0" value={d.couponMinOrder} onChange={e=>change('couponMinOrder',Number(e.target.value))}/></Field></div>
 <div className="pub-actions">{['tr','fa','en','ru'].map(l=><Toggle key={l} label={l.toUpperCase()} checked={d.languages?.includes(l)} onChange={on=>change('languages',on?[...(d.languages||[]),l]:d.languages.filter((x:string)=>x!==l))}/>)}</div>
 <div className="pub-form-grid">{['tr','fa','en','ru'].map(l=><Field key={l} label={tr(['کلیدواژه','Keyword','Anahtar kelime','Ключевое слово'])+' · '+l.toUpperCase()}><input value={d.keywords?.[l]||''} onChange={e=>change('keywords',{...d.keywords,[l]:e.target.value})}/></Field>)}</div>
 <div className="pub-policy-group"><h3>{tr(['گیت و کوپن','Gate & coupon','Koşullar ve kupon','Условия и купон'])}</h3><Toggle label={tr(['Follow فقط با سیگنال رسمی تأیید شود','Require a verified follow signal','Doğrulanmış takip sinyali iste','Требовать проверенный сигнал подписки'])} checked={d.requireVerifiedFollow} onChange={v=>change('requireVerifiedFollow',v)}/><Toggle label={tr(['خوداظهاری Like در فعال‌سازی لازم باشد','Require Like self-declaration at activation','Etkinleştirmede beğeni beyanı iste','Требовать заявление о лайке'])} checked={d.requireLikeAttestation} onChange={v=>change('requireLikeAttestation',v)}/><Toggle label={tr(['کوپن برای دوست فعال باشد','Enable friend coupon','Arkadaş kuponunu etkinleştir','Включить купон друга'])} checked={d.couponEnabled} onChange={v=>change('couponEnabled',v)}/><div className="pub-form-grid"><Field label={tr(['مقدار کوپن','Coupon value','Kupon değeri','Размер купона'])}><input type="number" min="0" value={d.couponValue} onChange={e=>change('couponValue',Number(e.target.value))}/></Field><Field label={tr(['نوع','Type','Tür','Тип'])}><select value={d.couponType} onChange={e=>change('couponType',e.target.value)}><option value="percent">%</option><option value="fixed">TL</option></select></Field><Field label={tr(['اعتبار کوپن (روز)','Coupon validity (days)','Kupon süresi (gün)','Срок купона (дни)'])}><input type="number" min="1" max="365" value={d.couponDays} onChange={e=>change('couponDays',Number(e.target.value))}/></Field></div></div>
 <details className="pub-policy-group"><summary>{tr(['سیاست مالی — نیازمند تأیید مالک','Financial policy — owner approval required','Mali politika — işletme onayı gerekli','Финансы — требуется одобрение владельца'])}</summary><p className="pub-note">{tr(['مشتری جدید: بدون پرداخت مثبت قبلی ثبت‌شده در سفارش‌ها یا سانس‌ها. تعامل اجتماعی کمیسیون ایجاد نمی‌کند.','New customer: no previous positive settled order/session. Social engagement never creates commission.','Yeni müşteri: önceden ödenmiş sipariş/seans yok. Sosyal etkileşim komisyon oluşturmaz.','Новый клиент: нет прежних оплаченных заказов/сеансов. Социальные действия не создают комиссию.'])}</p><div className="pub-form-grid">{[
  ['commissionPct',tr(['کمیسیون مشتری جدید (%)','New customer commission (%)','Yeni müşteri komisyonu (%)','Комиссия нового клиента (%)'])],['refundDays',tr(['مهلت بازپرداخت (روز)','Refund hold (days)','İade bekleme (gün)','Срок возврата (дни)'])],['attributionDays',tr(['پنجره انتساب (روز)','Attribution window (days)','İlişkilendirme süresi (gün)','Окно атрибуции (дни)'])],['payoutMin',tr(['حداقل تسویه (TL)','Minimum settlement (TL)','Minimum mutabakat (TL)','Минимальный расчёт (TL)'])],
 ].map(([k,label])=><Field key={k} label={label}><input type="number" min="0" value={d[k]} onChange={e=>change(k,Number(e.target.value))}/></Field>)}<Field label={tr(['مسئول تأیید مالی','Financial approver','Mali onay sorumlusu','Ответственный за финансы'])}><input value={d.responsible||''} onChange={e=>change('responsible',e.target.value)}/></Field></div><Toggle label={tr(['این سیاست مالی توسط مالک تأیید شده است','The business owner approved this financial policy','İşletme sahibi mali politikayı onayladı','Владелец одобрил финансовую политику'])} checked={d.financialApproved} onChange={v=>change('financialApproved',v)}/></details>
 <details className="pub-policy-group"><summary>{tr(['متن‌های چهارزبانه و دکمه','Four-language messages & button','Dört dilde mesaj ve düğme','Сообщения и кнопка на четырёх языках'])}</summary><div className="pub-actions">{['fa','tr','en','ru'].map(l=><button type="button" className={lang===l?'pub-primary':'pub-secondary'} key={l} onClick={()=>setLang(l)}>{l.toUpperCase()}</button>)}</div>{[['partner1',tr(['پیام اول همکار','Partner message 1','Ortak mesajı 1','Сообщение партнёру 1'])],['partner2',tr(['پیام دوم همکار — بدون لینک','Partner message 2 — no private link','Ortak mesajı 2 — özel bağlantı yok','Сообщение партнёру 2 — без ссылки'])],['friend',tr(['پیام دوست','Friend message','Arkadaş mesajı','Сообщение другу'])],['invite',tr(['لینک فقط برای دوست','Link for friend only','Bağlantı yalnızca arkadaşa','Ссылка только другу'])],['button',tr(['عنوان دکمه','Button label','Düğme etiketi','Текст кнопки'])]].map(([key,label])=><Field label={label} key={key}><textarea rows={key==='button'?1:4} value={d.messages?.[lang]?.[key]||''} onChange={e=>change('messages',{...d.messages,[lang]:{...d.messages[lang],[key]:e.target.value}})}/></Field>)}</details>
 <Toggle label={c('enabled')} checked={d.active} onChange={v=>change('active',v)}/><div className="pub-safety"><Toggle label={tr(['حساب، متن‌ها، زبان و شرایط این نسخه را بررسی و تأیید کردم.','I reviewed and approved this version’s account, messages, languages and conditions.','Bu sürümün hesap, mesaj, dil ve koşullarını onaylıyorum.','Я проверил и одобрил аккаунт, тексты, языки и условия этой версии.'])} checked={v.confirmed} onChange={confirmed=>setV({...v,confirmed})}/></div><button className="pub-primary" disabled={busy||d.active&&!v.confirmed}>{c('save')}</button>
 </form>;
}

function OutboxResolveForm({busy,save}:any){const {tr}=useCopy();const [messageId,setMessageId]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false);return <form onSubmit={e=>{e.preventDefault();void save({messageId,note,confirmed});}}><p className="pub-note">{tr(['فقط وقتی پیام را در Zernio/گفتگوی درست مشاهده کرده‌اید تأیید کنید. این عمل پیام تازه‌ای نمی‌فرستد. متن یا لینک خصوصی پیام را اینجا ننویسید.','Confirm only after observing the message in the correct Zernio conversation. This sends no new message. Do not paste private message text or links.','Yalnızca doğru Zernio konuşmasında mesajı gördükten sonra onaylayın. Yeni mesaj gönderilmez; özel metin/bağlantı yapıştırmayın.','Подтверждайте только увиденное сообщение в правильном диалоге Zernio. Новое сообщение не отправляется. Не вставляйте личные тексты и ссылки.'])}</p><Field label={tr(['شناسه پیام در سرویس','Provider message ID','Servis mesaj ID','ID сообщения сервиса'])}><input required value={messageId} onChange={e=>setMessageId(e.target.value)}/></Field><Field label={tr(['یادداشت بررسی (فقط هش ذخیره می‌شود)','Review note (only its hash is stored)','İnceleme notu (yalnızca özeti saklanır)','Примечание (хранится только хэш)'])}><textarea required value={note} onChange={e=>setNote(e.target.value)} maxLength={500}/></Field><Toggle label={tr(['همین پیام و گیرنده را بررسی کردم.','I verified this message and recipient.','Bu mesajı ve alıcıyı kontrol ettim.','Я проверил это сообщение и получателя.'])} checked={confirmed} onChange={setConfirmed}/><button className="pub-primary" disabled={!confirmed||busy}>{tr(['ثبت تأیید اپراتور','Record operator confirmation','Operatör onayını kaydet','Записать подтверждение оператора'])}</button></form>;}
