import React,{useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import {useOps} from '../management/context';
export const COPY={
  title:['استودیوی انتشار','Publishing studio','Yayın stüdyosu','Студия публикаций'],
  overview:['نمای کلی','Overview','Genel bakış','Обзор'],posts:['پست‌ها','Posts','Gönderiler','Публикации'],campaigns:['کمپین‌ها','Campaigns','Kampanyalar','Кампании'],media:['رسانه‌های مجاز','Approved media','Onaylı medya','Разрешённые медиа'],agents:['عامل‌ها','Agents','Aracılar','Агенты'],settings:['اتصال و تنظیمات','Connections','Bağlantılar','Подключения'],events:['رویدادها','Events','Olaylar','События'],telegram:['تلگرام','Telegram','Telegram','Телеграм'],legacy:['بلاگ و محتوای قبلی','Blog & earlier content','Blog ve önceki içerik','Блог и прежние материалы'],
  save:['ذخیره تغییرات','Save changes','Kaydet','Сохранить'],cancel:['انصراف','Cancel','İptal','Отмена'],close:['بستن','Close','Kapat','Закрыть'],edit:['ویرایش','Edit','Düzenle','Изменить'],name:['نام','Name','Ad','Название'],enabled:['فعال','Enabled','Etkin','Включено'],disabled:['غیرفعال','Disabled','Devre dışı','Отключено'],manual:['دستی','Manual','Manuel','Вручную'],agent:['توسط عامل','By agent','Aracı ile','Агентом'],none:['انتخاب نشده','Not selected','Seçilmedi','Не выбрано'],default:['پیش‌فرض','Default','Varsayılan','По умолчанию'],add:['افزودن','Add','Ekle','Добавить'],loading:['در حال دریافت…','Loading…','Yükleniyor…','Загрузка…'],empty:['هنوز موردی ثبت نشده','Nothing here yet','Henüz kayıt yok','Пока записей нет'],refresh:['به‌روزرسانی','Refresh','Yenile','Обновить'],version:['نسخه','Version','Sürüm','Версия'],status:['وضعیت','Status','Durum','Статус'],back:['بازگشت','Back','Geri','Назад'],
};
export function useCopy(){const ops=useOps();const tr=(v:readonly string[])=>({fa:v[0],en:v[1],tr:v[2],ru:v[3]}[ops.language]||v[1]);return {...ops,tr,c:(key:keyof typeof COPY)=>tr(COPY[key])};}
export function StateBadge({value}:{value:string}){
 const {tr}=useCopy();const labels:Record<string,string[]>={partial:['انتشار بخشی از مقصدها','Partially published','Kısmen yayınlandı','Частично опубликовано'],stored:['ذخیره‌شده','Stored','Kayıtlı','Сохранено'],partner_follow_pending:['در انتظار دکمهٔ همکار','Partner follow pending','Ortak takibi bekliyor','Ожидается ответ партнёра'],friend_follow_pending:['در انتظار دکمهٔ دوست','Friend follow pending','Arkadaş takibi bekliyor','Ожидается ответ друга'],code_ready:['کد در صف','Code queued','Kod kuyrukta','Код в очереди'],code_sent:['کد ارسال شد','Code sent','Kod gönderildi','Код отправлен'],link_ready:['لینک در صف','Link queued','Bağlantı kuyrukta','Ссылка в очереди'],link_sent:['لینک برای دوست ارسال شد','Friend link sent','Arkadaş bağlantısı gönderildi','Ссылка другу отправлена'],activated:['فعال‌شده','Activated','Etkinleştirildi','Активировано'],processing:['در حال پردازش','Processing','İşleniyor','Обработка'],waiting_media:['در انتظار رسانهٔ مجاز','Waiting for media approval','Medya onayı bekleniyor','Ожидается одобрение медиа'],blocked:['متوقف','Blocked','Engellendi','Заблокировано'],expired:['منقضی','Expired','Süresi doldu','Истекло'],scheduled:['زمان‌بندی‌شده','Scheduled','Planlandı','Запланировано'],submitted:['ارسال به سرویس','Submitted','Servise gönderildi','Передано сервису'],cancelled:['لغوشده','Cancelled','İptal edildi','Отменено'],credential_unavailable:['کلید قابل خواندن نیست','Credential unavailable','Anahtar okunamıyor','Ключ недоступен'],uploading:['در حال بارگذاری','Uploading','Yükleniyor','Загрузка'],validating:['بررسی فایل','Validating','Doğrulanıyor','Проверка'],ready:['آماده','Ready','Hazır','Готово'],unconfigured:['نیازمند کلید','Key required','Anahtar gerekli','Нужен ключ'],configured_untested:['ذخیره‌شده؛ بررسی‌نشده','Configured · untested','Ayarlı · test edilmedi','Настроено · не проверено'],connection_failed:['خطای اتصال','Connection failed','Bağlantı hatası','Ошибка соединения'],disabled:['غیرفعال','Disabled','Devre dışı','Отключено'],unsupported:['نیازمند آداپتور','Adapter required','Adaptör gerekli','Нужен адаптер'],pending:['در انتظار','Pending','Bekliyor','Ожидает'],queued:['در صف','Queued','Kuyrukta','В очереди'],approved:['تأییدشده','Approved','Onaylı','Одобрено'],needs_review:['نیازمند بررسی','Needs review','İnceleme gerekli','Нужна проверка'],deleted:['حذف‌شده','Deleted','Silindi','Удалено'],draft:['پیش‌نویس','Draft','Taslak','Черновик'],published:['منتشرشده','Published','Yayınlandı','Опубликовано'],delivery_unknown:['نتیجه نامشخص','Delivery unknown','Sonuç belirsiz','Результат неизвестен'],sent:['ارسال‌شده','Sent','Gönderildi','Отправлено'],failed:['ناموفق','Failed','Başarısız','Ошибка'],done:['انجام‌شده','Done','Tamamlandı','Выполнено'],ignored:['نادیده گرفته شد','Ignored','Yok sayıldı','Пропущено']};
 return <span className={`pub-badge ${['ready','approved','published','sent','done'].includes(value)?'good':['failed','connection_failed','delivery_unknown'].includes(value)?'bad':'muted'}`}>{labels[value]?tr(labels[value]):value.replaceAll('_',' ')}</span>;
}
export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <label className="pub-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Toggle({label,checked,onChange,disabled=false}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <label className="pub-toggle"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} disabled={disabled}/><span>{label}</span></label>;}
export function PubModal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){
 const {c,language}=useCopy();const ref=useRef<HTMLElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';
  const focusables=()=>Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')||[]).filter(e=>e.offsetParent!==null);
  focusables()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close.current();if(e.key==='Tab'){const els=focusables(),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
  document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus();};
 },[]);
 return createPortal(<div className="pub-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={ref} role="dialog" aria-modal="true" aria-label={title} className="pub-app pub-modal" dir={language==='fa'?'rtl':'ltr'}><header><h2>{title}</h2><button type="button" className="pub-icon-button" onClick={onClose} aria-label={c('close')}>×</button></header>{children}</section></div>,document.body);
}
export function ErrorNotice({error}:{error:string}){const {tr}=useCopy();if(!error)return null;const messages:Record<string,string[]>={SECRETS_KEY_REQUIRED:['کلید اصلی رمزگذاری روی هاست تنظیم نشده؛ ذخیرهٔ متن ساده مجاز نیست.','Set the host encryption key before saving credentials. Plaintext storage is blocked.','Kimlik bilgilerini kaydetmeden önce şifreleme anahtarını ayarlayın.','Сначала настройте ключ шифрования на хосте. Открытое хранение запрещено.'],HOST_MANAGED:['این مقدار از هاست خوانده می‌شود. برای انتقال به پنل، منبع هاست را صریحاً تغییر دهید.','This credential is host-managed. Explicitly migrate its source before panel changes.','Bu bilgi sunucudan yönetiliyor. Kaynağı açıkça taşıyın.','Этот ключ управляется хостом. Сначала перенесите источник.'],VERSION_CONFLICT:['نسخه تغییر کرده است؛ دوباره دریافت کنید.','This item changed. Reload before editing.','Kayıt değişti. Yenileyin.','Версия изменилась. Обновите данные.'],AGENT_KEY_REQUIRED:['کلید عامل تنظیم نشده است.','The agent API key is not configured.','Aracı API anahtarı ayarlı değil.','API-ключ агента не настроен.']};return <div className="pub-alert" role="alert">{messages[error]?tr(messages[error]):tr(['عملیات تکمیل نشد','Action could not be completed','İşlem tamamlanamadı','Не удалось завершить действие'])}<code>{error}</code></div>;}
