import React,{useEffect,useState} from 'react';
import {ShieldCheck,Users,Gift,ArrowRight,Check,LockKeyhole,Globe} from 'lucide-react';
import {useLanguage} from '../../context/LanguageContext';
import logo from '../../assets/images/bazino_logo_user-80.webp';
import './inviteGate.css';
export default function InviteGate({id,token,user,onAuth,onNavigate}:{id:string;token:string;user:any;onAuth:()=>void;onNavigate:(p:string)=>void}){
  const {language,setLanguage}=useLanguage();
  const t=(fa:string,en:string,tr:string,ru:string)=>({fa,en,tr,ru}[language]||en);
  const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[liked,setLiked]=useState(false),[handle,setHandle]=useState(''),[result,setResult]=useState<any>(null);
  const errors:Record<string,string>={
    INVITE_INVALID_OR_EXPIRED:t('دعوت معتبر نیست یا منقضی شده است.','This invitation is invalid or expired.','Davet geçersiz veya süresi dolmuş.','Приглашение недействительно или истекло.'),
    INVITE_ALREADY_CLAIMED:t('این دعوت قبلاً استفاده شده است.','This invitation has already been claimed.','Bu davet zaten kullanıldı.','Это приглашение уже использовано.'),
    PHONE_VERIFICATION_REQUIRED:t('ابتدا با کد پیامکی وارد شوید.','Please sign in with a verification code first.','Önce doğrulama koduyla giriş yapın.','Сначала войдите с кодом подтверждения.'),
    STAFF_NOT_ELIGIBLE:t('حساب کارکنان مشمول این پیشنهاد نیست.','Staff accounts are not eligible.','Personel hesapları uygun değil.','Предложение недоступно сотрудникам.'),
    CAMPAIGN_ALREADY_CLAIMED:t('سهمیهٔ این کمپین قبلاً برای حساب شما فعال شده است.','You already claimed this campaign.','Bu kampanyayı zaten kullandınız.','Вы уже воспользовались этой кампанией.'),
  };
  const load=()=>{setError('');fetch(`/api/instagram/invites/${encodeURIComponent(id)}?token=${encodeURIComponent(token)}`,{cache:'no-store',referrerPolicy:'no-referrer'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}).catch(e=>setError(e.message));};
  useEffect(load,[id,token,user?.username,user?.phoneVerified]);
  async function activate(){setBusy(true);setError('');try{const r=await fetch(`/api/instagram/invites/${encodeURIComponent(id)}/claim`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,consent,likeAttested:liked,handle}),referrerPolicy:'no-referrer'});const d=await r.json();if(!r.ok)throw Error(d.error);setResult(d);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <main className="invite-gate" dir={language==='fa'?'rtl':'ltr'}>
    <header className="ig-brand"><a href="/" aria-label="Bazino home"><img src={logo} alt="Bazino"/><strong>BAZINO <span>PRO</span></strong></a><div className="ig-language"><Globe size={16}/>{(['tr','fa','en','ru'] as const).map(l=><button key={l} className={l===language?'chosen':''} onClick={()=>setLanguage(l)}>{{tr:'🇹🇷',fa:'🇮🇷',en:'🇬🇧',ru:'🇷🇺'}[l]} {l.toUpperCase()}</button>)}</div></header>
    <section className="ig-welcome"><span className="ig-eyebrow">INVITE YOUR SQUAD</span><h1>{t('جای تو در جمع ما خالی‌ست.','Your squad is waiting.','Takımın seni bekliyor.','Твоя команда ждёт.')}</h1><p>{t('دعوت دوستت را در چند گام ساده فعال کن.','Activate your friend’s invitation in a few simple steps.','Arkadaşının davetini birkaç adımda etkinleştir.','Активируй приглашение друга за несколько шагов.')}</p></section>
    {error&&<div role="alert" className="ig-alert">{errors[error]||t('عملیات انجام نشد. دوباره تلاش کنید.','We couldn’t complete this action. Try again.','İşlem tamamlanamadı. Yeniden deneyin.','Не удалось завершить действие. Повторите попытку.')}<button onClick={load}>{t('بررسی دوباره','Retry','Tekrar','Повторить')}</button></div>}
    {!data&&!error&&<div className="ig-card" aria-busy="true">{t('در حال بررسی دعوت…','Checking your invitation…','Davet kontrol ediliyor…','Проверяем приглашение…')}</div>}
    {data&&<div className="ig-columns"><section className="ig-card ig-progress">
      <div className="ig-icon"><Users size={24}/></div><h2>{data.campaign}</h2>
      <div className="ig-step"><Check size={18}/><div><b>{t('کد دوستت ثبت شده','Friend code received','Arkadaş kodu alındı','Код друга получен')}</b><p>{t('کامنت کد زیر همان پست، شاهد عملی کمپین است؛ نه تأیید فردی Share توسط Meta.','Your code comment is indirect campaign evidence, not individual Share verification by Meta.','Kod yorumun dolaylı kampanya kanıtıdır; Meta paylaşım doğrulaması değildir.','Комментарий — косвенное свидетельство, не проверка Share от Meta.')}</p></div></div>
      <div className="ig-step"><ShieldCheck size={18}/><div><b>{data.followMethod==='follow_verified'?t('سیگنال Follow تأیید شده','Follow signal verified','Takip sinyali doğrulandı','Сигнал подписки подтверждён'):t('تأیید دکمهٔ «فالو دارم»','“I followed” button received','Takip onayı düğmesi alındı','Получена кнопка подтверждения')}</b><p>{data.followMethod==='follow_verified'?t('سیگنال قابل‌پشتیبانی سرویس ثبت شد.','A supported provider signal was recorded.','Desteklenen servis sinyali kaydedildi.','Записан поддерживаемый сигнал сервиса.'):t('این مرحله خوداظهاری است، نه اثبات قطعی Follow با API.','This is a self-declaration, not a verified API follow check.','Bu bir beyan; kesin API takip doğrulaması değil.','Это заявление, а не подтверждённая API-проверка.')}</p></div></div>
      <p className="ig-private"><LockKeyhole size={16}/>{t('رمز اینستاگرام شما را هرگز نمی‌خواهیم.','We never ask for your Instagram password.','Instagram şifrenizi asla istemiyoruz.','Мы не запрашиваем пароль Instagram.')}</p>
    </section><section className="ig-card ig-claim">
      <div className="ig-icon gift"><Gift size={24}/></div><h2>{t('فعال‌سازی دعوت','Activate invitation','Daveti etkinleştir','Активировать приглашение')}</h2>
      {data.coupon.enabled?<div className="ig-offer"><strong>{data.coupon.value}{data.coupon.type==='percent'?'%':' TL'}</strong><span>{t('کوپن یک‌بارمصرف رزرو، پس از تکمیل شرایط','One-time booking coupon after completing the conditions','Koşullar tamamlanınca tek kullanımlık rezervasyon kuponu','Одноразовый купон на бронь после выполнения условий')}</span><small>{t('حداقل رزرو','Minimum booking','Minimum rezervasyon','Минимальная бронь')}: {data.coupon.minOrder} TL · {data.coupon.validDays} {t('روز اعتبار','days validity','gün geçerli','дней действия')}</small></div>:<p className="ig-note">{t('این کمپین در حال حاضر کوپن فعال ندارد؛ دعوت شما برای انتساب رزرو ثبت می‌شود.','This campaign currently has no coupon. Your invitation can still be attributed to a booking.','Şu anda kupon yok; davetiniz rezervasyona ilişkilendirilebilir.','Сейчас купона нет; приглашение можно связать с бронью.')}</p>}
      {result?<div className="ig-result" data-invite-result><ShieldCheck size={32}/><h3>{t('دعوت شما فعال شد','Invitation activated','Davet etkinleştirildi','Приглашение активировано')}</h3>{result.coupon&&<><code>{result.coupon.code}</code><p>{t('این کوپن مخصوص حساب شماست.','This coupon is bound to your account.','Kupon hesabınıza özeldir.','Купон привязан к вашему аккаунту.')}</p></>}<button className="ig-primary" onClick={()=>onNavigate('/reservations')}>{t('انتخاب زمان بازی','Book your play time','Oyun saatini seç','Забронировать время')}<ArrowRight size={18}/></button></div>:<>
        {(data.needsLogin||data.needsPhoneVerification)?<button className="ig-primary" onClick={onAuth}>{t('ورود با کد پیامکی','Sign in with SMS code','SMS koduyla giriş','Войти с SMS-кодом')}</button>:<form onSubmit={e=>{e.preventDefault();void activate();}}>
          <label className="ig-field">{t('نام کاربری اینستاگرام (اختیاری)','Instagram handle (optional)','Instagram adı (isteğe bağlı)','Имя Instagram (необязательно)')}<input dir="ltr" autoComplete="off" placeholder="@your_handle" value={handle} maxLength={31} onChange={e=>setHandle(e.target.value)}/></label>
          <label className="ig-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>{t('با ثبت این اطلاعات برای دعوت، انتساب رزرو و شرایط کمپین موافقم. داشتن لینک، اثبات مالکیت حساب اینستاگرام نیست.','I consent to recording this information for the invitation, booking attribution and campaign conditions. Possessing the link does not verify Instagram account ownership.','Bilgilerin davet, rezervasyon ilişkilendirmesi ve kampanya için kaydına onay veriyorum. Bağlantıya sahip olmak Instagram hesabı sahipliğini doğrulamaz.','Согласен на запись данных для приглашения, атрибуции и условий кампании. Ссылка не подтверждает владение Instagram.')}</span></label>
          {data.requireLikeAttestation&&<label className="ig-check"><input type="checkbox" checked={liked} onChange={e=>setLiked(e.target.checked)} required/><span>{t('اعلام می‌کنم پست را Like کرده‌ام — خوداظهاری، بدون تأیید API.','I declare that I liked the post — self-reported, not API-verified.','Gönderiyi beğendiğimi beyan ediyorum — API doğrulaması değildir.','Заявляю, что поставил лайк — это не API-проверка.')}</span></label>}
          <button className="ig-primary" disabled={busy||!consent||data.requireLikeAttestation&&!liked}>{busy?t('در حال ثبت…','Activating…','Etkinleştiriliyor…','Активация…'):t('تأیید و فعال‌سازی','Confirm and activate','Onayla ve etkinleştir','Подтвердить и активировать')}</button>
        </form>}
      </>}
    </section></div>}
    <footer className="ig-footer">BAZINO PRO · {t('دعوت خصوصی. شرایط شفاف.','Private invitation. Clear conditions.','Özel davet. Açık koşullar.','Личное приглашение. Ясные условия.')} <a href="/legal/affiliate">{t('قوانین همکاری','Affiliate terms','Ortaklık koşulları','Условия партнёрства')}</a></footer>
  </main>;
}
