import React,{useState} from 'react';
import {useOps,useResource,Screen,Notice,Money,Badge,SyncState} from './context';
import {Dialog} from './Payment';
import {WalletConsole} from './Wallet';
export function AffiliateConsole(){
 const {api,t,can,language,timezone}=useOps(),[since,setSince]=useState(''),list=useResource<any>('/affiliates'+(since?'?since='+since:'')),customers=useResource<any[]>('/customers');
 const [selected,setSelected]=useState(''),detail=useResource<any>(selected?`/affiliates/${selected}`:null),[edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState<any>(null),[attach,setAttach]=useState(false),[reject,setReject]=useState<any>(null);
 const rates=[['newPct',t('درصد مشتری جدید','New customer %','Yeni müşteri %','% нового клиента')],['returnPct',t('درصد بازگشتی','Returning %','Geri dönen %','% повторного клиента')],['tournamentPct',t('درصد مسابقه','Tournament %','Turnuva %','% турнира')],['overridePct',t('درصد بالاسری','Parent %','Üst ortak %','% вышестоящего')]];
 const status=(s:string)=>({pending:t('در انتظار','Pending','Bekliyor','Ожидает'),approved:t('تأییدشده','Approved','Onaylandı','Одобрено'),paid_out:t('واریزشده به کیف پول','Credited to wallet','Cüzdana aktarıldı','Зачислено в кошелек'),reversed:t('برگشت‌شده','Reversed','Geri alındı','Отменено'),rejected:t('ردشده','Rejected','Reddedildi','Отклонено')}[s]||s);
 async function act(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();await list.reload();await detail.reload();}catch(e:any){setError(e.code||e.message);}finally{setBusy(false);}}
 return <Screen title={t('همکاری در فروش','Affiliates','Satış ortaklığı','Партнерская программа')} subtitle={t('کد معرفی، کمیسیون و کیف پول؛ واریز به کیف پول با نقدکردن یکی نیست.','Referrals, commissions and wallet. Wallet credit is not a cash payout.','Referanslar, komisyon ve cüzdan. Cüzdan kredisi nakit ödeme değildir.','Рефералы, комиссии и кошелек. Зачисление не означает выдачу наличных.')} actions={<><SyncState lastSync={list.lastSync} error={list.error}/><button onClick={()=>setSettings(list.data?.settings||{})}>{t('تنظیمات طرح','Program settings','Program ayarları','Настройки программы')}</button><button className="ops-primary" onClick={()=>setEdit({name:'',code:'',username:'',status:'active',parentId:'',newPct:-1,returnPct:-1,tournamentPct:-1,overridePct:-1})}>{t('همکار جدید','New affiliate','Yeni ortak','Новый партнер')}</button></>}>
 <Notice error={error||list.error||detail.error}/><div className="ops-grid">{[['netSales',t('فروش منتسب','Attributed sales','Atfedilen satışlar','Реферальные продажи')],['pending',t('کمیسیون در انتظار','Pending commission','Bekleyen komisyon','Ожидающая комиссия')],['paidOut',t('واریز به کیف پول','Wallet credits','Cüzdan kredileri','Зачисления в кошелек')],['reversed',t('برگشت کمیسیون','Reversed commission','Geri alınan komisyon','Возвращенная комиссия')]].map(([key,label])=><div className="ops-card" key={key}><p className="ops-muted">{label}</p><div className="ops-stat"><Money amount={list.data?.totals?.[key]||0}/></div></div>)}</div>
 <div className="ops-toolbar"><label>{t('از تاریخ','Since','Başlangıç','С даты')}<input type="date" value={since} onChange={e=>setSince(e.target.value)}/></label><button onClick={()=>setAttach(true)}>{t('ثبت معرف مشتری حضوری','Assign walk-in referral','Yerinde müşteri referansı','Реферал клиента на месте')}</button></div>
 <div className="ops-table-wrap"><table><thead><tr><th>{t('همکار','Affiliate','Ortak','Партнер')}</th><th>{t('کد / حساب','Code / account','Kod / hesap','Код / счет')}</th><th>{t('معرفی / پرداخت','Leads / paid','Müşteri / ödeme','Клиенты / оплаты')}</th><th>{t('کیف پول / در انتظار','Wallet / pending','Cüzdan / bekleyen','Кошелек / ожидание')}</th><th></th></tr></thead><tbody>{(list.data?.affiliates||[]).map((a:any)=><tr key={a.id} data-affiliate-row={a.id}><td><b>{a.name}</b><Badge tone={a.status==='active'?'good':'warn'}>{a.status==='active'?t('فعال','Active','Aktif','Активен'):t('متوقف','Paused','Duraklatıldı','Приостановлен')}</Badge></td><td><div className="ops-code">{a.code}</div><div>{a.username||'—'}</div></td><td>{a.stats.leads} / {a.stats.paid}</td><td><Money amount={a.stats.paidOut}/> / <Money amount={a.stats.pending}/></td><td><div className="ops-actions"><button onClick={()=>setSelected(a.id)}>{t('جزئیات و کیف پول','Details & wallet','Ayrıntılar ve cüzdan','Подробности и кошелек')}</button><button onClick={()=>setEdit(a)}>{t('ویرایش','Edit','Düzenle','Изменить')}</button></div></td></tr>)}</tbody></table></div>
 {detail.data&&<div className="ops-card"><div className="ops-row"><h3>{detail.data.affiliate.name}</h3><button className="ops-quiet" onClick={()=>setSelected('')}>×</button></div><p className="ops-code">{`${detail.data.affiliate.destination||'/'}${(detail.data.affiliate.destination||'/').includes('?')?'&':'?'}ref=${encodeURIComponent(detail.data.affiliate.code)}`}</p><p className="ops-muted">{t('مسیر لینک معرفی روی دامنهٔ سایت خودتان؛ از نشانی محلی صندوق برای اشتراک استفاده نکنید.','Use this referral path on your public website, not the cashier’s local address.','Bu referans yolunu kasa adresinde değil, genel sitenizde kullanın.','Используйте этот путь на публичном сайте, а не локальном адресе кассы.')}</p>
 <div className="ops-table-wrap"><table><thead><tr><th>{t('سفارش','Order','Sipariş','Заказ')}</th><th>{t('کمیسیون','Commission','Komisyon','Комиссия')}</th><th>{t('وضعیت','Status','Durum','Статус')}</th><th></th></tr></thead><tbody>{detail.data.commissions.map((c:any)=><tr key={c.id}><td className="ops-code">{c.orderId}</td><td><Money amount={c.commissionAmount}/><div>{c.ratePct}%</div></td><td><Badge tone={c.status==='paid_out'?'good':'warn'}>{status(c.status)}</Badge>{c.flag&&<p className="ops-code">{c.flag}</p>}</td><td>{c.status==='pending'&&<div className="ops-actions"><button disabled={busy} onClick={()=>act(()=>api(`/affiliate-commissions/${c.id}/approve`,'POST',{}))}>{t('تأیید کمیسیون','Approve','Onayla','Одобрить')}</button><button className="ops-danger" onClick={()=>setReject(c)}>{t('رد','Reject','Reddet','Отклонить')}</button></div>}</td></tr>)}</tbody></table></div>
 <details className="ops-card"><summary>{t('معرفی‌شدگان و تاریخچه','Referrals & history','Referanslar ve geçmiş','Рефералы и история')}</summary>{detail.data.attributions.map((a:any)=><p key={a.id}>{a.username} · {a.source}</p>)}{detail.data.audit.map((a:any)=><p key={a.id}>{new Date(a.createdAt).toLocaleString(language,{timeZone:timezone})} · {a.actor} · {a.action}</p>)}</details>
 {detail.data.affiliate.username&&(can('wallet')||can('cashout'))&&<WalletConsole username={detail.data.affiliate.username} compact/>}</div>}
 {edit&&<Dialog title={t('اطلاعات همکار','Affiliate details','Ortak bilgileri','Данные партнера')} onClose={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();void act(async()=>{await api('/affiliates','POST',edit);setEdit(null);});}}><div className="ops-form-grid"><label>{t('نام','Name','Ad','Имя')}<input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>{t('کد معرفی','Referral code','Referans kodu','Реферальный код')}<input required value={edit.code} maxLength={20} onChange={e=>setEdit({...edit,code:e.target.value.toUpperCase()})}/></label><label>{t('حساب کیف پول','Wallet account','Cüzdan hesabı','Счет кошелька')}<select value={edit.username} onChange={e=>setEdit({...edit,username:e.target.value})}><option value="">—</option>{(customers.data||[]).map(c=><option key={c.username} value={c.username}>{c.displayName} — {c.username}</option>)}</select></label><label>{t('وضعیت','Status','Durum','Статус')}<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="active">{t('فعال','Active','Aktif','Активен')}</option><option value="paused">{t('متوقف','Paused','Duraklatıldı','Приостановлен')}</option></select></label><label className="ops-span">{t('همکار بالاسری (اختیاری)','Parent affiliate (optional)','Üst ortak (isteğe bağlı)','Вышестоящий партнер (необязательно)')}<select value={edit.parentId||''} onChange={e=>setEdit({...edit,parentId:e.target.value})}><option value="">—</option>{(list.data?.affiliates||[]).filter((a:any)=>a.id!==edit.id&&!a.parentId).map((a:any)=><option key={a.id} value={a.id}>{a.name} · {a.code}</option>)}</select></label>{rates.map(([key,label])=><label key={key}>{label}<input type="number" min="-1" max="100" step="0.1" value={edit[key]} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}</div><p className="ops-muted">{t('مقدار ‎−۱ یعنی استفاده از نرخ سراسری موجود.','−1 inherits the existing global rate.','−1 mevcut genel oranı kullanır.','−1 использует действующую общую ставку.')}</p><Notice error={error}/><button className="ops-primary" disabled={busy}>{t('ذخیره','Save','Kaydet','Сохранить')}</button></form></Dialog>}
 {settings&&<Dialog title={t('تنظیمات طرح','Program settings','Program ayarları','Настройки программы')} onClose={()=>setSettings(null)}><form onSubmit={e=>{e.preventDefault();void act(async()=>{await api('/affiliate-settings','POST',{settings});setSettings(null);});}}>{Object.entries(settings).map(([k,v])=><label key={k}>{k}<input value={String(v)} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}<Notice error={error}/><button className="ops-primary" disabled={busy}>{t('ذخیره','Save','Kaydet','Сохранить')}</button></form></Dialog>}
 {attach&&<Dialog title={t('معرف مشتری حضوری','Walk-in referral','Yerinde referans','Реферал на месте')} onClose={()=>setAttach(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await api('/affiliate-attach','POST',{username:f.get('username'),code:f.get('code')});setAttach(false);});}}><label>{t('مشتری','Customer','Müşteri','Клиент')}<select name="username" required>{(customers.data||[]).map(c=><option key={c.username} value={c.username}>{c.displayName}</option>)}</select></label><label>{t('کد معرفی','Referral code','Referans kodu','Реферальный код')}<input name="code" required/></label><Notice error={error}/><button disabled={busy}>{t('ثبت','Save','Kaydet','Сохранить')}</button></form></Dialog>}
 {reject&&<Dialog title={t('رد کمیسیون','Reject commission','Komisyonu reddet','Отклонить комиссию')} onClose={()=>setReject(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await api(`/affiliate-commissions/${reject.id}/reject`,'POST',{note:f.get('note')});setReject(null);});}}><label>{t('دلیل','Reason','Neden','Причина')}<input name="note" required/></label><Notice error={error}/><button className="ops-danger" disabled={busy}>{t('رد','Reject','Reddet','Отклонить')}</button></form></Dialog>}
 </Screen>;
}
