import React,{useEffect,useState} from 'react';
import {useOps,useResource,Screen,Notice,Money,Badge,SyncState} from './context';
import {Dialog,PaymentDialog,ReceiptView} from './Payment';
import type {Receipt} from './types';
export function OrdersConsole({kind,defaultStationId,defaultSessionId}:{kind:'cafe'|'shop';defaultStationId?:string;defaultSessionId?:string}){
 const {api,t,can,language,timezone}=useOps();
 const orders=useResource<any[]>(`/orders?kind=${kind}`),catalog=useResource<any[]>(`/catalog/${kind}`),context=useResource<any>('/order-context'),customers=useResource<any[]>('/customers');
 const [tab,setTab]=useState<'orders'|'new'|'catalog'>('orders'),[search,setSearch]=useState(''),[source,setSource]=useState('all'),[filterStatus,setFilterStatus]=useState('all'),[stationFilter,setStationFilter]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [station,setStation]=useState(defaultStationId||''),[session,setSession]=useState(defaultSessionId||''),[username,setUsername]=useState(''),[name,setName]=useState(''),[coupon,setCoupon]=useState(''),[product,setProduct]=useState(''),[cart,setCart]=useState<Array<{id:string;quantity:number}>>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[payment,setPayment]=useState<any>(null),[receipt,setReceipt]=useState<Receipt|null>(null),[edit,setEdit]=useState<any>(null),[action,setAction]=useState<any>(null),[attach,setAttach]=useState<any>(null);
 useEffect(()=>{if(defaultStationId){setStation(defaultStationId);setSession(defaultSessionId||'');setTab('new');}},[defaultStationId,defaultSessionId]);
 const label=(s:string)=>({new:t('جدید','New','Yeni','Новый'),accepted:t('پذیرفته‌شده','Accepted','Kabul edildi','Принят'),preparing:t('در حال آماده‌سازی','Preparing','Hazırlanıyor','Готовится'),ready:t('آمادهٔ تحویل','Ready','Hazır','Готов'),delivered:t('تحویل‌شده','Delivered','Teslim edildi','Выдан'),cancelled:t('لغوشده','Cancelled','İptal','Отменен'),returned:t('مرجوعی','Returned','İade','Возврат')}[s]||s);
 const paymentLabel=(s:string)=>({paid:t('پرداخت‌شده','Paid','Ödendi','Оплачен'),free:t('رایگان','Free','Ücretsiz','Бесплатно'),pending:t('پرداخت‌نشده','Unpaid','Ödenmedi','Не оплачен'),refunded:t('مستردشده','Refunded','İade edildi','Возвращено'),cancelled:t('لغوشده','Cancelled','İptal','Отменен'),unknown:t('سابقهٔ قدیمی؛ نیازمند تطبیق','Legacy; reconcile first','Eski kayıt; mutabakat gerekli','Старая запись; нужна сверка')}[s]||s);
 const filtered=(orders.data||[]).filter(o=>(source==='all'||o.source===source)&&(!stationFilter||o.stationId===stationFilter)&&(filterStatus==='all'||o.fulfilmentStatus===filterStatus)&&(!search||`${o.id} ${o.customerName} ${o.stationName}`.toLowerCase().includes(search.toLowerCase()))&&(!from||o.createdAt>=from)&&(!to||o.createdAt<to+'T23:59:59.999Z'));
 async function act(fn:()=>Promise<any>){setBusy(true);setError('');setSuccess('');try{await fn();await orders.reload();await catalog.reload();}catch(e:any){setError(e.code||e.message);}finally{setBusy(false);}}
 async function advance(o:any,status:string,extra:any={}){return api(`/orders/${o.id}/status`,'POST',{status,version:o.version,...extra});}
 async function collect(o:any){await act(async()=>{if(o.fulfilmentStatus==='new')await advance(o,'accepted');setPayment(o);});}
 return <Screen title={kind==='cafe'?t('کافه و سفارش‌ها','Café & orders','Kafe ve siparişler','Кафе и заказы'):t('فروشگاه و سفارش‌ها','Shop & orders','Mağaza ve siparişler','Магазин и заказы')} subtitle={t('سفارش آنلاین و حضوری، موجودی مشترک و ارتباط روشن با ایستگاه.','Online and walk-in orders, shared stock and explicit station links.','Çevrimiçi ve yerinde siparişler, ortak stok ve açık istasyon bağlantıları.','Онлайн-заказы и продажи на месте, общий склад и связь со станциями.')} actions={<SyncState lastSync={orders.lastSync} error={orders.error}/> }>
 <Notice error={error||orders.error||catalog.error} success={success}/>
 <div className="ops-tabs" role="tablist">{(['orders','new','catalog'] as const).map(v=><button key={v} aria-selected={tab===v} onClick={()=>setTab(v)}>{v==='orders'?t('صف سفارش‌ها','Order queue','Sipariş kuyruğu','Очередь заказов'):v==='new'?t('ثبت سفارش حضوری','New walk-in order','Yeni yerinde sipariş','Продажа на месте'):t('کالا و موجودی','Catalog & stock','Ürünler ve stok','Товары и склад')}</button>)}</div>
 {tab==='orders'&&<><div className="ops-toolbar"><input aria-label="order-search" placeholder={t('جست‌وجوی سفارش یا مشتری','Order or customer search','Sipariş veya müşteri ara','Поиск заказа или клиента')} value={search} onChange={e=>setSearch(e.target.value)}/><select value={source} onChange={e=>setSource(e.target.value)}><option value="all">{t('همهٔ منابع','All sources','Tüm kaynaklar','Все источники')}</option><option value="online">{t('آنلاین','Online','Çevrimiçi','Онлайн')}</option><option value="onsite">{t('حضوری','Walk-in','Yerinde','На месте')}</option><option value="legacy">{t('قدیمی','Legacy','Eski','Старые')}</option></select><select value={stationFilter} onChange={e=>setStationFilter(e.target.value)}><option value="">{t('همهٔ ایستگاه‌ها','All stations','Tüm istasyonlar','Все станции')}</option>{(context.data?.stations||[]).map((s:any)=><option key={s.id} value={s.id}>{s.data.name}</option>)}</select><select value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="all">{t('همهٔ وضعیت‌ها','All states','Tüm durumlar','Все статусы')}</option>{['new','accepted','preparing','ready','delivered','cancelled','returned'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select><input type="date" aria-label="orders-from" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" aria-label="orders-to" value={to} onChange={e=>setTo(e.target.value)}/></div>
 <div className="ops-table-wrap"><table><thead><tr><th>{t('سفارش / اقلام','Order / items','Sipariş / ürünler','Заказ / товары')}</th><th>{t('مشتری / ایستگاه','Customer / station','Müşteri / istasyon','Клиент / станция')}</th><th>{t('مبلغ و پرداخت','Amount & payment','Tutar ve ödeme','Сумма и оплата')}</th><th>{t('آماده‌سازی','Fulfilment','Hazırlık','Выполнение')}</th><th>{t('عملیات','Actions','İşlemler','Действия')}</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} data-order-row={o.id}><td><Badge tone={o.source==='online'?'info':'neutral'}>{o.source==='online'?t('آنلاین','Online','Çevrimiçi','Онлайн'):o.source==='onsite'?t('حضوری','Walk-in','Yerinde','На месте'):t('قدیمی','Legacy','Eski','Старый')}</Badge><div className="ops-code">{o.id}</div>{o.lines.map((l:any,i:number)=><div key={i}>{l.item?.name||l.name||l.item?.id} × {l.quantity}</div>)}<small className="ops-muted">{Number.isFinite(Date.parse(o.createdAt))?new Date(o.createdAt).toLocaleString(language,{timeZone:timezone}):o.createdAt}</small></td><td><b>{o.customerName}</b><p>{o.stationName||t('پیشخوان / مشتری آزاد','Counter / guest','Tezgah / misafir','Касса / гость')}</p>{o.sessionId&&<Badge tone="info">{t('متصل به سانس','On session bill','Seans hesabında','В счете сеанса')}</Badge>}</td><td><Money amount={o.amount}/><div><Badge tone={['paid','free'].includes(o.paymentStatus)?'good':o.paymentStatus==='pending'?'warn':'neutral'}>{paymentLabel(o.paymentStatus)}</Badge></div></td><td>{label(o.fulfilmentStatus)}</td><td><div className="ops-actions">{!o.legacy&&<>
 {o.fulfilmentStatus==='new'&&<button disabled={busy} onClick={()=>act(()=>advance(o,'accepted'))}>{t('پذیرش','Accept','Kabul et','Принять')}</button>}
 {o.fulfilmentStatus==='accepted'&&<button disabled={busy} onClick={()=>act(()=>advance(o,kind==='cafe'?'preparing':'ready'))}>{kind==='cafe'?t('آماده‌سازی','Prepare','Hazırla','Готовить'):label('ready')}</button>}
 {o.fulfilmentStatus==='preparing'&&<button disabled={busy} onClick={()=>act(()=>advance(o,'ready'))}>{label('ready')}</button>}
 {o.fulfilmentStatus==='ready'&&<button disabled={busy} onClick={()=>act(()=>advance(o,'delivered'))}>{t('تحویل','Deliver','Teslim et','Выдать')}</button>}
 {o.paymentStatus==='pending'&&can('collect')&&<button className="ops-primary" disabled={busy} onClick={()=>collect(o)}>{t('دریافت وجه','Collect','Tahsil et','Принять оплату')}</button>}
 {o.paymentStatus==='pending'&&!['cancelled','delivered'].includes(o.fulfilmentStatus)&&<><button disabled={busy} onClick={()=>setAttach(o)}>{t('اتصال به سانس','Attach to session','Seansa bağla','Привязать к сеансу')}</button><button className="ops-danger" disabled={busy} onClick={()=>setAction({order:o,status:'cancelled'})}>{t('لغو','Cancel','İptal','Отмена')}</button></>}
 {kind==='shop'&&o.fulfilmentStatus==='delivered'&&can('collect')&&<button className="ops-danger" disabled={busy} onClick={()=>setAction({order:o,status:'returned'})}>{t('مرجوعی کامل','Full return','Tam iade','Полный возврат')}</button>}
 </>}</div></td></tr>)}{!filtered.length&&<tr><td colSpan={5}>{t('سفارشی مطابق فیلتر نیست.','No matching orders.','Eşleşen sipariş yok.','Нет подходящих заказов.')}</td></tr>}</tbody></table></div></>}
 {tab==='new'&&<form className="ops-card" onSubmit={e=>{e.preventDefault();void act(async()=>{const r=await api('/orders','POST',{kind,username,customerName:name,stationId:station||null,sessionId:session||null,couponCode:coupon,lines:cart.map(l=>({item:{id:l.id},quantity:l.quantity}))});setSuccess(`${t('سفارش ثبت شد؛ هنوز پرداخت نشده','Order created; unpaid','Sipariş kaydedildi; ödenmedi','Заказ создан; не оплачен')} · ${r.id}`);setCart([]);setTab('orders');});}}><div className="ops-form-grid"><label>{t('حساب مشتری','Customer account','Müşteri hesabı','Счет клиента')}<select value={username} onChange={e=>setUsername(e.target.value)}><option value="">{t('مشتری آزاد','Guest','Misafir','Гость')}</option>{(customers.data||[]).map(c=><option key={c.username} value={c.username}>{c.displayName} — {c.username}</option>)}</select></label><label>{t('نام مشتری آزاد','Guest name','Misafir adı','Имя гостя')}<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label>{t('ایستگاه تحویل (اختیاری)','Delivery station (optional)','Teslim istasyonu (isteğe bağlı)','Станция выдачи (необязательно)')}<select value={station} onChange={e=>{setStation(e.target.value);setSession('');}} data-order-station><option value="">{t('پیشخوان','Counter','Tezgah','Касса')}</option>{(context.data?.stations||[]).map((s:any)=><option key={s.id} value={s.id}>{s.data.name}</option>)}</select></label><label>{t('افزودن طلب به سانس (اختیاری)','Bill on session (optional)','Seans hesabına ekle (isteğe bağlı)','Добавить в счет сеанса (необязательно)')}<select value={session} onChange={e=>setSession(e.target.value)} data-order-session><option value="">{t('دریافت مستقل','Separate payment','Ayrı ödeme','Отдельная оплата')}</option>{(context.data?.sessions||[]).filter((s:any)=>s.stationId===station).map((s:any)=><option key={s.id} value={s.id}>{s.customerName} — {s.id.slice(-8)}</option>)}</select></label></div>
 <div className="ops-toolbar"><select value={product} onChange={e=>setProduct(e.target.value)} data-order-product><option value="">{t('انتخاب کالا','Choose product','Ürün seç','Выбрать товар')}</option>{(catalog.data||[]).map(p=><option key={p.id} value={p.id}>{p.name} · {p.price} TRY · {p.stock}</option>)}</select><button type="button" disabled={!product} onClick={()=>{setCart(prev=>prev.some(p=>p.id===product)?prev.map(p=>p.id===product?{...p,quantity:p.quantity+1}:p):[...prev,{id:product,quantity:1}]);setProduct('');}}>{t('افزودن','Add','Ekle','Добавить')}</button></div>
 <div className="ops-stack" style={{margin:'15px 0'}}>{cart.map(l=><div className="ops-row" key={l.id}><span>{catalog.data?.find(p=>p.id===l.id)?.name}</span><input style={{width:100}} type="number" min="1" max="1000" step="1" value={l.quantity} onChange={e=>setCart(cart.map(p=>p.id===l.id?{...p,quantity:Number(e.target.value)}:p))}/><button type="button" onClick={()=>setCart(cart.filter(p=>p.id!==l.id))}>×</button></div>)}</div><label>{t('کوپن تخفیف (اختیاری)','Discount code (optional)','İndirim kodu (isteğe bağlı)','Промокод (необязательно)')}<input value={coupon} onChange={e=>setCoupon(e.target.value)} maxLength={50}/></label><p className="ops-muted">{t('مبلغ نهایی و موجودی روی سرور کنترل می‌شود. ثبت سفارش، پرداخت محسوب نمی‌شود.','The server checks the final amount and stock. Creating an order is not payment.','Son tutar ve stok sunucuda kontrol edilir. Sipariş oluşturmak ödeme değildir.','Сервер проверяет итог и остатки. Создание заказа не означает оплату.')}</p><button className="ops-primary" disabled={busy||!cart.length}>{t('ثبت سفارش','Create order','Sipariş oluştur','Создать заказ')}</button></form>}
 {tab==='catalog'&&<><div className="ops-actions">{can('configure')&&<button className="ops-primary" onClick={()=>setEdit({name:'',price:0,stock:0,category:kind==='cafe'?'Drinks':'Controller',version:0})}>{t('کالای جدید','New product','Yeni ürün','Новый товар')}</button>}</div><div className="ops-grid">{(catalog.data||[]).map(p=><article className="ops-card" key={p.id}><div className="ops-row"><h3>{p.name}</h3>{p.imageUrl&&<img className="ops-img" src={p.imageUrl} alt=""/>}</div><div className="ops-code">{p.id}</div><div className="ops-row"><Money amount={p.price}/><Badge tone={p.stock?'info':'bad'}>{t('موجودی','Stock','Stok','Остаток')}: {p.stock}</Badge></div>{can('configure')&&<button onClick={()=>setEdit(p)}>{t('ویرایش / موجودی','Edit / stock','Düzenle / stok','Изменить / склад')}</button>}</article>)}</div></>}
 {payment&&<PaymentDialog title={t('دریافت سفارش','Order payment','Sipariş ödemesi','Оплата заказа')} amount={payment.amount} onClose={()=>setPayment(null)} onSubmit={async b=>{const r=await api(`/onsite-orders/${payment.id}/settle`,'POST',b);setReceipt(r.receipt||null);await orders.reload();}}/>}{receipt&&<ReceiptView receipt={receipt} onClose={()=>setReceipt(null)}/>}
 {edit&&<Dialog title={t('کالا و موجودی','Product & stock','Ürün ve stok','Товар и склад')} onClose={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();void act(async()=>{await api(`/catalog/${kind}`,'POST',edit);setEdit(null);});}}><div className="ops-form-grid">{[['name',t('نام','Name','Ad','Название')],['category',t('دسته','Category','Kategori','Категория')],['price',t('قیمت TRY','Price TRY','Fiyat TRY','Цена TRY')],['stock',t('موجودی قابل فروش','Available stock','Satılabilir stok','Доступный остаток')]].map(([key,label])=><label key={key}>{label}<input type={key==='price'||key==='stock'?'number':'text'} min="0" step={key==='price'?'0.01':'1'} required value={edit[key]} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}<label className="ops-span">{t('آدرس تصویر (اختیاری)','Image URL (optional)','Görsel URL (isteğe bağlı)','URL изображения (необязательно)')}<input value={edit.imageUrl||''} onChange={e=>setEdit({...edit,imageUrl:e.target.value})}/></label></div><Notice error={error}/><button className="ops-primary" disabled={busy}>{t('ذخیره','Save','Kaydet','Сохранить')}</button></form></Dialog>}
 {action&&<Dialog title={label(action.status)} onClose={()=>setAction(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await advance(action.order,action.status,{note:f.get('note'),discard:f.get('discard')==='on',restock:f.get('restock')==='on',confirmed:f.get('confirmed')==='on'});setAction(null);});}}><p>{t('این عملیات و دلیل آن در تاریخچه ثبت می‌شود.','This action and reason are audited.','Bu işlem ve nedeni kaydedilir.','Действие и причина сохраняются в журнале.')}</p><label>{t('دلیل','Reason','Neden','Причина')}<input name="note" required maxLength={500}/></label>{action.status==='cancelled'&&['preparing','ready'].includes(action.order.fulfilmentStatus)&&<label className="ops-check"><input name="discard" type="checkbox" required/>{t('مواد مصرف شده‌اند؛ موجودی خودکار برنگردد.','Materials used; do not restock automatically.','Malzeme kullanıldı; stok otomatik dönmesin.','Материалы использованы; не возвращать автоматически на склад.')}</label>}{action.status==='returned'&&<><label className="ops-check"><input type="checkbox" name="restock"/>{t('کالای سالم واقعاً به انبار برگشت.','Saleable goods were returned to stock.','Satılabilir ürün stoka döndü.','Пригодный товар возвращен на склад.')}</label>{action.order.paymentStatus==='paid'&&<label className="ops-check"><input type="checkbox" name="confirmed" required/>{t('کل مبلغ نقداً به خریدار مسترد شد؛ این عملیات بازپرداخت بانکی نیست.','The full amount was refunded in cash; this is not a bank reversal.','Tutarın tamamı nakit iade edildi; bu banka iptali değildir.','Вся сумма возвращена наличными; это не банковская отмена.')}</label>}</>}<Notice error={error}/><button className="ops-danger" disabled={busy}>{t('تأیید','Confirm','Onayla','Подтвердить')}</button></form></Dialog>}
 {attach&&<Dialog title={t('اتصال به صورت‌حساب سانس','Attach to session bill','Seans hesabına bağla','Привязать к счету сеанса')} onClose={()=>setAttach(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await api(`/orders/${attach.id}/attach`,'POST',{sessionId:f.get('session')});setAttach(null);});}}><label>{t('سانس فعال','Active session','Aktif seans','Активный сеанс')}<select required name="session"><option value="">—</option>{(context.data?.sessions||[]).map((s:any)=><option key={s.id} value={s.id}>{context.data.stations.find((st:any)=>st.id===s.stationId)?.data.name} · {s.customerName}</option>)}</select></label><Notice error={error}/><button disabled={busy}>{t('ثبت اتصال','Attach','Bağla','Привязать')}</button></form></Dialog>}
 </Screen>;
}
