import React, { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Money, Notice, useOps } from './context';
import type { Receipt } from './types';
export function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
  const latest=useRef(onClose);latest.current=onClose;const ref=useRef<HTMLDivElement>(null);const {language,t}=useOps();
  useEffect(()=>{const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLElement>('button,input,select,textarea')?.focus();
    const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();latest.current();}if(e.key==='Tab'){const items=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')||[]) as HTMLElement[];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus?.();};},[]);
  return createPortal(<div className="ops ops-overlay" dir={language==='fa'?'rtl':'ltr'} onMouseDown={e=>{if(e.target===e.currentTarget)latest.current();}}><div className="ops-dialog" ref={ref} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" className="ops-quiet" onClick={onClose} aria-label={t('بستن','Close','Kapat','Закрыть')}>×</button></header>{children}</div></div>,document.body);
}
export function PaymentDialog({title,amount,onClose,onSubmit,outgoing=false}:{title:string;amount:number;onClose:()=>void;onSubmit:(data:any)=>Promise<any>;outgoing?:boolean}){
  const {t}=useOps();const [method,setMethod]=useState<'cash'|'pos'>('cash'),[reference,setReference]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <Dialog title={title} onClose={()=>{if(!busy)onClose();}}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSubmit({method,reference,note,confirmed:amount===0||confirmed});onClose();}catch(err:any){setError(err.code||err.message);}finally{setBusy(false);}}}>
    <div className="ops-card ops-row"><span>{outgoing?t('وجه خروجی','Cash out','Nakit çıkış','Выдача наличных'):t('مبلغ قابل دریافت','Amount due','Ödenecek tutar','К оплате')}</span><Money amount={amount}/></div>
    {amount>0&&!outgoing&&<div className="ops-tabs" style={{margin:'16px 0'}}>{(['cash','pos'] as const).map(m=><button key={m} type="button" aria-selected={method===m} onClick={()=>setMethod(m)} data-ops-method={m}>{m==='cash'?t('نقدی','Cash','Nakit','Наличные'):t('دستگاه POS','POS terminal','POS cihazı','POS-терминал')}</button>)}</div>}
    {method==='pos'&&!outgoing&&<p className="ops-notice ops-warning">{t('ثبت دستی POS: مبلغ را روی دستگاه دریافت کنید، سپس موفقیت رسید را تأیید کنید. این دکمه به دستگاه فرمان نمی‌فرستد.','Manual POS record: verify the terminal receipt first. This button does not charge a card.','Manuel POS kaydı: önce cihaz makbuzunu doğrulayın. Bu düğme karttan ödeme almaz.','Ручная запись POS: сначала проверьте чек терминала. Эта кнопка не списывает деньги с карты.')}</p>}
    {amount===0?<p className="ops-notice ops-success">{t('بدون دریافت وجه — مبلغ نهایی صفر است.','No collection — zero total.','Tahsilat yok — toplam sıfır.','Без оплаты — нулевая сумма.')}</p>:<><label>{t('مرجع رسید (اختیاری، بدون اطلاعات کارت)','Receipt reference (optional; no card data)','Makbuz referansı (isteğe bağlı; kart bilgisi yok)','Номер чека (необязательно; без данных карты)')}<input value={reference} onChange={e=>setReference(e.target.value)} maxLength={80}/></label><label className="ops-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required data-ops-confirm/><span>{outgoing?t('وجه نقد به صاحب حساب تحویل داده شد.','Cash has been handed to the account holder.','Nakit hesap sahibine teslim edildi.','Наличные выданы владельцу счета.'):t('دریافت واقعی وجه را تأیید می‌کنم.','I confirm the money was actually received.','Paranın gerçekten alındığını onaylıyorum.','Подтверждаю фактическое получение средств.')}</span></label></>}
    <label>{t('توضیح','Note','Not','Примечание')}<input value={note} onChange={e=>setNote(e.target.value)} maxLength={500}/></label><Notice error={error}/><div className="ops-actions"><button className="ops-primary" disabled={busy||(amount>0&&!confirmed)}>{busy?t('در حال ثبت…','Saving…','Kaydediliyor…','Сохранение…'):t('ثبت نهایی','Confirm','Onayla','Подтвердить')}</button><button type="button" disabled={busy} onClick={onClose}>{t('بازگشت','Back','Geri','Назад')}</button></div>
  </form></Dialog>;
}
export function ReceiptView({receipt,onClose}:{receipt:Receipt;onClose:()=>void}){const {t,language,timezone}=useOps();return <Dialog title={t('رسید عملیاتی بازینو','Bazino receipt','Bazino makbuzu','Чек Bazino')} onClose={onClose}><div className="ops-receipt"><h3>BAZINO PRO</h3><div className="ops-code">{receipt.id}</div><div className="ops-row"><span>{receipt.direction==='out'?t('پرداخت نقدی خروجی','Cash payout','Nakit ödeme','Выдача наличных'):t('دریافت وجه','Collection','Tahsilat','Получено')}</span><Money amount={receipt.amount}/></div><p>{receipt.method==='pos'?t('POS — تأیید دستی اپراتور','POS — operator confirmation','POS — operatör onayı','POS — подтверждено оператором'):t('نقدی','Cash','Nakit','Наличные')}</p><p>{t('حساب','Account','Hesap','Счет')}: {receipt.username||'—'}</p><p>{t('اپراتور','Operator','Operatör','Оператор')}: {receipt.actor}</p><p>{new Date(receipt.createdAt).toLocaleString(language,{timeZone:timezone})}</p>{receipt.reference&&<p>{t('مرجع','Reference','Referans','Номер')}: {receipt.reference}</p>}{receipt.orderId&&<p className="ops-code">{receipt.orderId}</p>}{receipt.note&&<p>{receipt.note}</p>}<small>{t('رسید ثبت عملیات نرم‌افزار؛ جایگزین رسید بانکی یا سند مالیاتی نیست.','Operational record; not a replacement for bank or fiscal receipts.','İşlem kaydı; banka veya mali fiş yerine geçmez.','Запись операции; не заменяет банковский или фискальный чек.')}</small><div><button onClick={()=>window.print()}>{t('چاپ','Print','Yazdır','Печать')}</button></div></div></Dialog>;}
