import React, { useState } from 'react';
import { useOps, useResource, Screen, Notice, Badge, SyncState } from './context';
export function StationRegistry({localStations=[]}:{localStations?:any[]}) {
  const {api,t,can}=useOps(),{data,error,lastSync,reload}=useResource<any>('/bootstrap');
  const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[problem,setProblem]=useState('');
  const [editing,setEditing]=useState<Record<string,any>>({});
  async function act(id:string,fn:()=>Promise<any>){setBusy(id);setProblem('');setMessage('');try{await fn();setMessage(t('ذخیره شد.','Saved.','Kaydedildi.','Сохранено.'));setEditing({});await reload();}catch(e:any){setProblem(e.code||e.message);}finally{setBusy('');}}
  return <Screen title={t('اتصال ایستگاه‌ها به سایت','Station mapping','İstasyon eşleştirme','Связь станций')} subtitle={t('هر ایستگاه فقط به شناسهٔ انتخاب‌شده متصل می‌شود؛ تشابه نام‌ها باعث اتصال خودکار نمی‌شود.','Explicit one-to-one links. Names never determine the mapping.','Açık bire bir bağlantılar; adlar otomatik eşleştirilmez.','Явная связь один к одному. Названия не определяют связь.')} actions={<SyncState lastSync={lastSync} error={error} />}>
    <Notice error={problem||error} success={message}/>
    {can('configure')&&<div className="ops-card ops-row"><div><h3>{t('ثبت ایستگاه‌های این صندوق','Register this desk’s stations','Kasa istasyonlarını kaydet','Регистрация станций кассы')}</h3><p className="ops-muted">{t('اطلاعات موجود حفظ می‌شوند. ایستگاه‌های جدید ابتدا بدون اتصال به سایت ثبت می‌شوند.','Existing records are preserved; imported stations start unmapped.','Mevcut kayıtlar korunur; yeni istasyonlar eşleştirilmeden alınır.','Существующие записи сохраняются; новые станции не связаны автоматически.')}</p></div><button disabled={!!busy||!localStations.length} onClick={()=>act('import',()=>api('/stations/import','POST',{stations:localStations}))}>{t('واردکردن ایستگاه‌ها','Import stations','İstasyonları aktar','Импорт станций')}</button></div>}
    <div className="ops-table-wrap"><table><thead><tr><th>{t('ایستگاه مدیریت','Local station','Yerel istasyon','Локальная станция')}</th><th>{t('ایستگاه سایت','Website station','Site istasyonu','Станция сайта')}</th><th>{t('تعرفه ساعتی (TRY)','Hourly rate (TRY)','Saatlik ücret (TRY)','Тариф в час (TRY)')}</th><th></th></tr></thead><tbody>
    {(data?.stations||[]).map((r:any)=>{const value=editing[r.id]||r.data;return <tr key={r.id}><td><b>{r.data.name}</b><div className="ops-code">{r.id}</div>{!r.data.systemId&&<Badge tone="warn">{t('بدون اتصال','Unmapped','Eşleştirilmedi','Не связано')}</Badge>}</td><td><select disabled={!can('configure')} value={value.systemId||''} onChange={e=>setEditing({...editing,[r.id]:{...value,systemId:e.target.value||null}})} aria-label={`station-map-${r.id}`}><option value="">{t('انتخاب نشده','Not linked','Bağlanmadı','Не связано')}</option>{(data?.systems||[]).map((s:any)=><option key={s.id} value={s.id}>{s.name} — {s.id}</option>)}</select></td><td><input type="number" min="0" step="0.01" value={value.hourlyRate} disabled={!can('configure')} onChange={e=>setEditing({...editing,[r.id]:{...value,hourlyRate:Number(e.target.value)}})}/></td><td><button disabled={!!busy||!can('configure')||!editing[r.id]} onClick={()=>act(r.id,()=>api(`/stations/${encodeURIComponent(r.id)}`,'PUT',{...value,version:r.version}))}>{t('ذخیره','Save','Kaydet','Сохранить')}</button></td></tr>;})}
    {!data?.stations?.length&&<tr><td colSpan={4}>{t('هنوز ایستگاهی وارد نشده است.','No registered stations yet.','Henüz istasyon kaydedilmedi.','Нет зарегистрированных станций.')}</td></tr>}
    </tbody></table></div>
    {can('configure')&&data&&<form className="ops-card ops-row" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('config',()=>api('/config','PUT',{timezone:f.get('timezone'),version:data.config?.version||0}));}}><label>{t('منطقهٔ زمانی مجموعه','Venue timezone','Mekan saat dilimi','Часовой пояс клуба')}<select name="timezone" defaultValue={data.timezone}>{['Asia/Famagusta','Europe/Nicosia','Europe/Istanbul','Asia/Tehran','UTC'].map(z=><option key={z}>{z}</option>)}</select></label><button disabled={!!busy}>{t('ذخیره منطقهٔ زمانی','Save timezone','Saat dilimini kaydet','Сохранить часовой пояс')}</button></form>}
  </Screen>;
}
export function AccessManager(){const {api,t,staff}=useOps(),{data,error,reload}=useResource<any>(staff?.admin?'/access':null,0);const [problem,setProblem]=useState(''),[busy,setBusy]=useState('');
  if(!staff?.admin)return null;
  return <Screen title={t('دسترسی واقعی اپراتورها','Server-enforced staff access','Sunucu operatör yetkileri','Серверные права сотрудников')} subtitle={t('این دسترسی‌ها به حساب کاربری سایت متصل‌اند و در API هم بررسی می‌شوند.','Permissions are tied to the signed-in account and checked by the API.','Yetkiler oturum hesabına bağlıdır ve API tarafından doğrulanır.','Права связаны с учетной записью и проверяются API.')}><Notice error={problem||error}/><div className="ops-grid">{(data?.users||[]).map((u:any)=><form className="ops-card" key={u.username} onSubmit={async e=>{e.preventDefault();setBusy(u.username);setProblem('');const f=new FormData(e.currentTarget);try{await api(`/access/${encodeURIComponent(u.username)}`,'PUT',{permissions:f.getAll('permissions'),version:u.access?.version||0});await reload();}catch(err:any){setProblem(err.code);}finally{setBusy('');}}}><h3>{u.displayName} <span className="ops-code">{u.username}</span></h3>{u.role==='admin'?<Badge tone="good">{t('مدیر اصلی؛ همهٔ دسترسی‌ها','Administrator; all permissions','Yönetici; tüm yetkiler','Администратор; все права')}</Badge>:<><div className="ops-chip-selector">{(data?.permissions||[]).map((p:string)=><label key={p}><input name="permissions" value={p} type="checkbox" defaultChecked={u.access?.data?.permissions?.includes(p)}/>{p}</label>)}</div><button className="ops-primary" disabled={!!busy}>{t('ثبت دسترسی','Save access','Yetkileri kaydet','Сохранить права')}</button></>}</form>)}</div></Screen>;
}
