import React,{useState} from 'react';
import {useOps,useResource,Screen,Notice,Money,SyncState} from './context';
import {ReceiptView} from './Payment';
import type {Receipt} from './types';
export function safeCsvCell(v:unknown){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
export function ReportsConsole(){const {t,language,timezone}=useOps(),[from,setFrom]=useState(''),[to,setTo]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null);
 const resource=useResource<any>(`/reports?${new URLSearchParams({...from?{from}:{},...to?{to}:{}})}`,10000),d=resource.data;
 const names:Record<string,string>={reservation:t('رزرو ایستگاه','Reservations','Rezervasyonlar','Бронирования'),session:t('زمان جدید بازی','New play time','Yeni oyun süresi','Новое игровое время'),tournament:t('ورودی مسابقه','Tournament entries','Turnuva girişleri','Взносы турнира'),cafe:t('کافه','Café','Kafe','Кафе'),shop:t('فروشگاه','Shop','Mağaza','Магазин')};
 function download(){if(!d)return;const rows=[['receipt','time','action','direction','method','amount','currency','operator','reference'],...d.receipts.map((r:Receipt)=>[r.id,r.createdAt,r.action,r.direction,r.method,r.amount,r.currency,r.actor,r.reference])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(safeCsvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bazino-receipts-${d.from}-${d.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <Screen title={t('گزارش صندوق و فروش','Cash desk & sales','Kasa ve satış raporu','Касса и продажи')} subtitle={t('فروش، شارژ کیف پول و خروج نقد جدا محاسبه می‌شوند؛ جمع دریافت صندوق، سود یا فروش نیست.','Sales, wallet top-ups and cash payouts are separate. Till collections are not sales or profit.','Satış, cüzdan yükleme ve nakit çıkış ayrıdır. Kasa tahsilatı satış veya kâr değildir.','Продажи, пополнения и выдачи учитываются отдельно. Поступления в кассу не равны прибыли.')} actions={<><SyncState lastSync={resource.lastSync} error={resource.error}/><button onClick={download} disabled={!d}>CSV</button></>}>
 <Notice error={resource.error}/><div className="ops-toolbar"><label>{t('از','From','Başlangıç','С')}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{t('تا','To','Bitiş','По')}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{d&&<p className="ops-muted">{d.from} — {d.to} · {d.timezone}</p>}</div>
 <div className="ops-grid">{[['netSales',t('فروش خالص دوره','Net period sales','Dönem net satış','Чистые продажи периода')],['cashIn',t('دریافت نقدی','Cash received','Nakit tahsilat','Получено наличными')],['posIn',t('دریافت POS — دستی','POS received — manual','POS tahsilatı — manuel','Получено POS — вручную')],['cashOut',t('خروج نقد','Cash paid out','Nakit çıkış','Выдано наличными')],['customerLiability',t('تعهد کل به مشتریان','Customer liability','Müşteri yükümlülüğü','Обязательства перед клиентами')],['pendingCashouts',t('در انتظار تحویل نقد','Pending cash handover','Nakit teslimi bekliyor','Ожидает выдачи наличных')]].map(([k,label])=><div className="ops-card" key={k}><p className="ops-muted">{label}</p><div className="ops-stat"><Money amount={d?.[k]||0}/></div></div>)}</div>
 <div className="ops-card"><h3>{t('تفکیک فروش خدمات','Sales by service','Hizmete göre satış','Продажи по услугам')}</h3><div className="ops-grid">{Object.entries(d?.byKind||{}).map(([k,v])=><div className="ops-row" key={k}><span>{names[k]||k}</span><Money amount={Number(v)}/></div>)}</div><p className="ops-caption">{t('هزینهٔ رزرو قبلاً پرداخت‌شده دوباره در فروش سانس شمرده نمی‌شود؛ شارژ کیف پول هم فروش خدمت نیست.','Prepaid bookings are not counted again in session sales; wallet top-ups are not service sales.','Ön ödemeli rezervasyonlar tekrar sayılmaz; cüzdan yükleme hizmet satışı değildir.','Предоплаченные брони не учитываются повторно; пополнение кошелька не является продажей услуги.')}</p></div>
 <div className="ops-table-wrap"><table><thead><tr><th>{t('رسید','Receipt','Makbuz','Чек')}</th><th>{t('نوع / روش','Action / method','İşlem / yöntem','Операция / способ')}</th><th>{t('مبلغ','Amount','Tutar','Сумма')}</th><th>{t('زمان / اپراتور','Time / operator','Saat / operatör','Время / оператор')}</th><th></th></tr></thead><tbody>{(d?.receipts||[]).map((r:Receipt)=><tr key={r.id}><td className="ops-code">{r.id}</td><td>{r.action}<div>{r.direction==='in'?t('ورودی','In','Giriş','Приход'):t('خروجی','Out','Çıkış','Расход')} · {r.method==='pos'?'POS':t('نقدی','Cash','Nakit','Наличные')}</div></td><td><Money amount={r.amount}/></td><td>{new Date(r.createdAt).toLocaleString(language,{timeZone:timezone})}<div>{r.actor}</div></td><td><button onClick={()=>setReceipt(r)}>{t('نمایش / چاپ','View / print','Görüntüle / yazdır','Просмотр / печать')}</button></td></tr>)}</tbody></table></div>{receipt&&<ReceiptView receipt={receipt} onClose={()=>setReceipt(null)}/>}</Screen>;
}
