import React,{useEffect,useState} from 'react';
import {useOps,useResource,Notice,Badge,Money} from './context';
import {Dialog,PaymentDialog,ReceiptView} from './Payment';
import type {BookingView,Receipt} from './types';
export function StationReservations({reservations=[],onStart}:{reservations?:BookingView[];onStart:(r:BookingView)=>void}){
 const {api,t,timezone,can,language}=useOps(),[expanded,setExpanded]=useState(false),[payment,setPayment]=useState<BookingView|null>(null),[error,setError]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null),[busy,setBusy]=useState(false);
 const relevant=reservations.filter(r=>r.endsAt&&Date.parse(r.endsAt)>Date.now()&&!['cancelled','expired','completed'].includes(r.bookingStatus));
 if(!relevant.length)return null;
 const time=(iso:string|null)=>iso?new Date(iso).toLocaleTimeString(language,{timeZone:timezone,hour:'2-digit',minute:'2-digit'}):'—';
 return <div className="ops ops-reservation-strip" style={{padding:'0 12px 10px'}}><div className="ops-caption">{t('رزروهای این ایستگاه','Station reservations','İstasyon rezervasyonları','Бронирования станции')} ({relevant.length})</div><Notice error={error}/>{(expanded?relevant:relevant.slice(0,2)).map(r=><div className="ops-booking" key={r.id} data-station-booking={r.id}><div><time>{r.startsAt&&new Date(r.startsAt).toLocaleDateString(language,{timeZone:timezone,month:'short',day:'numeric'})} · {t('از','from','başlangıç','с')} <bdi dir="ltr">{time(r.startsAt)}</bdi> {t('تا','to','bitiş','до')} <bdi dir="ltr">{time(r.endsAt)}</bdi>{r.startsAt&&r.endsAt&&new Date(r.startsAt).toLocaleDateString('en',{timeZone:timezone})!==new Date(r.endsAt).toLocaleDateString('en',{timeZone:timezone})?t(' (روز بعد)',' (next day)',' (ertesi gün)',' (следующий день)'):''}</time></div><div>{r.customerName}</div><Badge tone={r.paymentStatus==='paid'||r.paymentStatus==='free'?'good':r.paymentStatus==='unknown'?'neutral':'warn'}>{r.paymentStatus==='paid'?t('قطعی — پرداخت‌شده','Confirmed — paid','Kesin — ödendi','Подтверждено — оплачено'):r.paymentStatus==='free'?t('قطعی — رایگان','Confirmed — free','Kesin — ücretsiz','Подтверждено — бесплатно'):r.paymentStatus==='unknown'?t('پرداخت نامشخص؛ سابقهٔ قدیمی','Payment unknown; legacy','Ödeme bilinmiyor; eski kayıt','Оплата неизвестна; старая запись'):t('در انتظار پرداخت','Awaiting payment','Ödeme bekliyor','Ожидает оплаты')}</Badge>{r.attendanceStatus!=='not_arrived'&&<Badge tone="info">{r.attendanceStatus==='playing'?t('در حال استفاده','Playing','Oynuyor','Идет сеанс'):t('حضور ثبت شده','Checked in','Giriş yapıldı','Прибыл')}</Badge>}
 <div className="ops-actions">{r.paymentStatus==='pending'&&r.orderId&&can('collect')&&<button disabled={!!r.paymentDueAt&&Date.parse(r.paymentDueAt)<=Date.now()} onClick={()=>setPayment(r)}>{t('دریافت وجه','Collect','Tahsil et','Принять оплату')}</button>}{r.bookingStatus==='confirmed'&&!r.sessionId&&can('reservations')&&<><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api(`/reservations/${r.id}/checkin`,'POST',{});}catch(e:any){setError(e.code);}finally{setBusy(false);}}}>{t('ثبت حضور','Check in','Giriş','Прибытие')}</button><button disabled={!!r.startsAt&&Date.now()<Date.parse(r.startsAt)-15*60000} onClick={()=>onStart(r)}>{t('شروع از رزرو','Start booking','Rezervasyonu başlat','Начать бронь')}</button></>}</div></div>)}{relevant.length>2&&<button className="ops-quiet" onClick={()=>setExpanded(!expanded)}>{expanded?t('کمتر','Less','Daha az','Меньше'):t('همهٔ رزروها','All reservations','Tüm rezervasyonlar','Все бронирования')}</button>}
 {payment&&<PaymentDialog title={t('دریافت رزرو','Reservation payment','Rezervasyon ödemesi','Оплата брони')} amount={payment.totalAmount-payment.paidAmount} onClose={()=>setPayment(null)} onSubmit={async b=>{const r=await api(`/onsite-orders/${payment.orderId}/settle`,'POST',b);setReceipt(r.receipt||null);}}/>}{receipt&&<ReceiptView receipt={receipt} onClose={()=>setReceipt(null)}/>}</div>;
}
export function StartSessionDialog({station,reservation,onClose,onStarted}:{station:any;reservation?:BookingView|null;onClose:()=>void;onStarted:()=>void}){
 const {api,t}=useOps(),customers=useResource<any[]>('/customers'),[minutes,setMinutes]=useState(60),[username,setUsername]=useState(reservation?.username||''),[name,setName]=useState(''),[controllers,setControllers]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog title={`${t('شروع سانس','Start session','Seansı başlat','Начать сеанс')} — ${station.name}`} onClose={()=>{if(!busy)onClose();}}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/sessions/start','POST',{stationId:station.id,username,customerName:name,durationMinutes:minutes,controllers,reservationId:reservation?.id});onStarted();onClose();}catch(err:any){setError(err.code);}finally{setBusy(false);}}}>
 {reservation?<div className="ops-notice ops-success">{t('رزرو پرداخت‌شده به همین سانس وصل می‌شود؛ فقط زمان اضافه و خرید جدید دریافت می‌شود.','The paid booking is linked; only overrun and new orders are collected.','Ödenmiş rezervasyon bağlanır; yalnızca ek süre ve siparişler tahsil edilir.','Оплаченная бронь привязана; оплачиваются только дополнительное время и покупки.')}</div>:<><label>{t('مدت سانس (دقیقه)','Duration (minutes)','Süre (dakika)','Длительность (минуты)')}<input type="number" min="1" max="1440" required value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>{t('حساب مشتری','Customer account','Müşteri hesabı','Счет клиента')}<select value={username} onChange={e=>setUsername(e.target.value)}><option value="">{t('مشتری آزاد','Walk-in','Misafir','Гость')}</option>{(customers.data||[]).map(c=><option key={c.username} value={c.username}>{c.displayName} — {c.username}</option>)}</select></label>{!username&&<label>{t('نام اختیاری','Optional name','İsteğe bağlı ad','Имя (необязательно)')}<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label>}<label>{t('تعداد دسته / بازیکن','Controllers / players','Kontrolcü / oyuncu','Контроллеры / игроки')}<select value={controllers} onChange={e=>setControllers(Number(e.target.value))}><option value={1}>1</option><option value={2}>2 · ×1.2</option><option value={4}>4 · ×1.5</option></select></label></>}
 <p className="ops-muted">{t('قیمت و تداخل زمانی روی سرور بررسی می‌شود. دریافت وجه در پایان با نقدی/POS ثبت می‌شود.','The server checks rates and conflicts. Collect cash/POS at checkout.','Ücret ve çakışma sunucuda kontrol edilir. Çıkışta nakit/POS tahsil edilir.','Сервер проверяет тариф и пересечения. Оплата наличными/POS в конце.')}</p><Notice error={error||customers.error}/><button className="ops-primary" disabled={busy}>{t('شروع سانس','Start session','Seansı başlat','Начать сеанс')}</button></form></Dialog>;
}
export function SessionCheckout({sessionId,onClose,onFinished}:{sessionId:string;onClose:()=>void;onFinished:()=>void}){
 const {api,t}=useOps(),[quote,setQuote]=useState<any>(null),[error,setError]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null),[done,setDone]=useState(false);
 useEffect(()=>{let cancelled=false;api(`/sessions/${sessionId}/quote`,'POST',{}).then(r=>{if(!cancelled)setQuote(r);}).catch(e=>{if(!cancelled)setError(e.code);});return()=>{cancelled=true;};},[sessionId]);
 if(receipt)return <ReceiptView receipt={receipt} onClose={()=>{setReceipt(null);onClose();}}/>;
 if(done)return null;
 if(!quote)return <Dialog title={t('محاسبهٔ صورت‌حساب','Calculating bill','Hesap hesaplanıyor','Расчет счета')} onClose={onClose}><Notice error={error}/>{!error&&<p>…</p>}</Dialog>;
 return <PaymentDialog autoClose={false} title={`${t('تسویهٔ سانس؛ پیش‌پرداخت','Checkout; already paid','Hesap; önceden ödenen','Расчет; уже оплачено')}: ${quote.data.quote.prepaidAmount} TRY`} amount={quote.data.quote.amount} onClose={()=>{if(!done)void api(`/sessions/${sessionId}/resume`,'POST',{}).catch(()=>{});onClose();}} onSubmit={async b=>{const r=await api(`/sessions/${sessionId}/finish`,'POST',{...b,version:quote.version});setDone(true);setReceipt(r.receipt||null);onFinished();if(!r.receipt)onClose();}}/>;
}
