import React, { useEffect, useState } from 'react';
import { useOps, useResource, Screen, Notice, Money, Badge, Empty, SyncState } from './context';
import { Dialog, PaymentDialog, ReceiptView } from './Payment';
import type { Receipt } from './types';
export function WalletConsole({username:initialUsername,compact=false}:{username?:string;compact?:boolean}){
  const {api,t,can,language,timezone}=useOps(),customers=useResource<any[]>('/customers'),[selected,setSelected]=useState(initialUsername||''),[search,setSearch]=useState('');
  const wallet=useResource<any>(selected?`/wallet/${encodeURIComponent(selected)}`:null),orders=useResource<any[]>(can('collect')&&!compact?'/onsite-orders':null);
  const [amount,setAmount]=useState(''),[mode,setMode]=useState<'topup'|'cashout'>('topup'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[payment,setPayment]=useState<any>(null),[receipt,setReceipt]=useState<Receipt|null>(null),[showNew,setShowNew]=useState(false),[cancel,setCancel]=useState<any>(null);
  useEffect(()=>{if(initialUsername)setSelected(initialUsername);},[initialUsername]);
  const filtered=(customers.data||[]).filter(c=>!search||`${c.username} ${c.displayName} ${c.phone}`.toLowerCase().includes(search.toLowerCase()));
  return <Screen title={t('کیف پول و صندوق حضوری','Wallet & front desk','Cüzdan ve kasa','Кошелек и касса')} subtitle={t('موجودی از سرور؛ شارژ با نقدی/POS و نقدکردن با ثبت تحویل وجه.','Server balance. Cash/POS top-ups and tracked cash handover.','Sunucu bakiyesi. Nakit/POS yükleme ve kayıtlı nakit teslimi.','Баланс сервера. Пополнение наличными/POS и учет выдачи.')} actions={<SyncState lastSync={wallet.lastSync||customers.lastSync} error={wallet.error||customers.error}/> }>
    <Notice error={error||wallet.error||customers.error} success={message}/>
    <div className={compact?'ops-stack':'ops-split'}><div className="ops-card"><h3>{t('انتخاب حساب','Select account','Hesap seç','Выбор счета')}</h3>{!initialUsername&&<><label>{t('جست‌وجوی نام یا شمارهٔ کامل','Name or full phone number','Ad veya tam telefon numarası','Имя или полный номер телефона')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label><select value={selected} onChange={e=>{setSelected(e.target.value);setError('');setMessage('');}} data-wallet-customer><option value="">{t('حساب را انتخاب کنید','Choose an account','Hesap seçin','Выберите счет')}</option>{filtered.map(c=><option key={c.username} value={c.username}>{c.displayName} — {c.phone||c.username}</option>)}</select>{can('wallet')&&<button style={{marginTop:12}} onClick={()=>setShowNew(true)}>{t('مشتری جدید','New customer','Yeni müşteri','Новый клиент')}</button>}</>}
      {wallet.data&&<div style={{marginTop:20}}><h3>{wallet.data.displayName}</h3><div className="ops-code">{wallet.data.username}</div><p className="ops-muted">{t('موجودی قابل مصرف / برداشت','Available balance','Kullanılabilir bakiye','Доступный баланс')}</p><div className="ops-stat"><Money amount={wallet.data.balance}/></div><div className="ops-tabs">{can('wallet')&&<button aria-selected={mode==='topup'} onClick={()=>setMode('topup')}>{t('شارژ','Top up','Yükle','Пополнить')}</button>}{can('cashout')&&<button aria-selected={mode==='cashout'} onClick={()=>setMode('cashout')}>{t('نقدکردن','Cash out','Nakit çek','Выдать наличные')}</button>}</div><form onSubmit={async e=>{e.preventDefault();setError('');setMessage('');if(mode==='topup'){setPayment({type:'topup',amount:Number(amount)});return;}setBusy(true);try{await api('/wallet/cashout','POST',{username:selected,amount:Number(amount)});setAmount('');setMessage(t('مبلغ رزرو شد؛ بعد از تحویل نقد، رسید خروجی را تأیید کنید.','Funds reserved. Confirm only after handing over cash.','Tutar ayrıldı. Nakdi teslim ettikten sonra onaylayın.','Средства зарезервированы. Подтвердите после выдачи наличных.'));await wallet.reload();}catch(err:any){setError(err.code);}finally{setBusy(false);}}}><label>{t('مبلغ (TRY)','Amount (TRY)','Tutar (TRY)','Сумма (TRY)')}<input type="number" step="0.01" min="0.01" required value={amount} onChange={e=>setAmount(e.target.value)} data-wallet-amount/></label><button className="ops-primary" disabled={busy||!!wallet.error||!(Number(amount)>0)}>{mode==='topup'?t('انتخاب روش دریافت','Choose collection method','Tahsilat yöntemi seç','Выбрать способ оплаты'):t('رزرو مبلغ برای تحویل نقد','Reserve cash payout','Nakit ödeme ayır','Зарезервировать выдачу')}</button></form><p className="ops-caption">{t('نقدکردن در حالت قطع ارتباط نهایی نمی‌شود.','Cash-out cannot be finalized offline.','Çevrimdışı nakit çekim tamamlanamaz.','Выдача наличных недоступна офлайн.')}</p></div>}
    </div><div className="ops-stack">{!selected?<Empty>{t('برای مشاهدهٔ گردش، یک حساب انتخاب کنید.','Select an account to view its ledger.','Hareketleri görmek için hesap seçin.','Выберите счет для просмотра операций.')}</Empty>:<>
      <div className="ops-card"><h3>{t('درخواست‌های نقدکردن','Cash-out requests','Nakit çekim talepleri','Запросы на выдачу')}</h3>{!wallet.data?.cashouts?.length?<p className="ops-muted">{t('درخواستی نیست.','No requests.','Talep yok.','Нет запросов.')}</p>:wallet.data.cashouts.map((r:any)=><div className="ops-card" key={r.id}><div className="ops-row"><Money amount={r.data.amount}/><Badge tone={r.data.status==='pending_handover'?'warn':r.data.status==='paid'?'good':'neutral'}>{r.data.status==='pending_handover'?t('در انتظار تحویل نقد','Awaiting cash handover','Nakit teslimi bekliyor','Ожидает выдачи'):r.data.status==='paid'?t('تحویل شد','Paid out','Teslim edildi','Выдано'):t('لغو شد','Cancelled','İptal','Отменено')}</Badge></div><div className="ops-code">{r.id}</div><div className="ops-actions">{r.data.status==='pending_handover'&&can('cashout')&&<><button onClick={()=>setPayment({type:'cashout',id:r.id,amount:r.data.amount})}>{t('تأیید تحویل وجه','Confirm handover','Teslimi onayla','Подтвердить выдачу')}</button><button className="ops-danger" onClick={()=>setCancel(r)}>{t('لغو و آزادسازی','Cancel & release','İptal ve serbest bırak','Отменить и вернуть')}</button></>}{r.data.receipt&&<button onClick={()=>setReceipt(r.data.receipt)}>{t('رسید','Receipt','Makbuz','Чек')}</button>}</div></div>)}</div>
      <div className="ops-card"><h3>{t('گردش معتبر کیف پول','Wallet ledger','Cüzdan hareketleri','Операции кошелька')}</h3><div className="ops-table-wrap"><table><thead><tr><th>{t('نوع','Type','Tür','Тип')}</th><th>{t('مبلغ','Amount','Tutar','Сумма')}</th><th>{t('مانده بعد','Balance after','Sonraki bakiye','Остаток')}</th><th>{t('زمان / اپراتور','Time / operator','Saat / operatör','Время / оператор')}</th></tr></thead><tbody>{(wallet.data?.transactions||[]).map((tx:any)=><tr key={tx.id}><td>{tx.type}<div className="ops-code">{tx.ref}</div></td><td><Money amount={tx.amount}/></td><td><Money amount={tx.balanceAfter}/></td><td>{new Date(tx.createdAt).toLocaleString(language,{timeZone:timezone})}<div>{tx.operator}</div></td></tr>)}</tbody></table></div></div>
    </>}</div></div>
    {!compact&&can('collect')&&<div className="ops-card"><h3>{t('سفارش‌های سایت در انتظار پرداخت حضوری','Online orders awaiting collection','Tahsilat bekleyen site siparişleri','Онлайн-заказы к оплате')}</h3><Notice error={orders.error}/><div className="ops-table-wrap"><table><thead><tr><th>{t('سفارش','Order','Sipariş','Заказ')}</th><th>{t('حساب','Account','Hesap','Счет')}</th><th>{t('مبلغ','Amount','Tutar','Сумма')}</th><th>{t('مهلت','Deadline','Son tarih','Срок')}</th><th></th></tr></thead><tbody>{(orders.data||[]).filter(o=>o.status==='pending_onsite').map(o=><tr key={o.id}><td>{o.description}<div className="ops-code">{o.id}</div></td><td>{o.username}</td><td><Money amount={o.amount}/></td><td>{o.dueAt?new Date(o.dueAt).toLocaleString(language,{timeZone:timezone}):'—'}</td><td><button disabled={!!o.dueAt&&Date.parse(o.dueAt)<=Date.now()} onClick={()=>setPayment({type:'order',id:o.id,amount:o.amount})}>{t('دریافت وجه','Collect','Tahsil et','Принять оплату')}</button></td></tr>)}</tbody></table></div></div>}
    {payment&&<PaymentDialog title={payment.type==='cashout'?t('تحویل نقد از کیف پول','Wallet cash handover','Cüzdandan nakit teslimi','Выдача наличных'):t('ثبت دریافت حضوری','Record collection','Tahsilat kaydı','Регистрация оплаты')} amount={payment.amount} outgoing={payment.type==='cashout'} onClose={()=>setPayment(null)} onSubmit={async b=>{const result=await api(payment.type==='topup'?'/wallet/topup':payment.type==='cashout'?`/cashouts/${payment.id}/confirm`:`/onsite-orders/${payment.id}/settle`,'POST',{...b,...(payment.type==='topup'?{username:selected,amount:payment.amount}:{})});setAmount('');setReceipt(result.receipt||result.data?.receipt||null);await wallet.reload();await orders.reload();}}/>}
    {receipt&&<ReceiptView receipt={receipt} onClose={()=>setReceipt(null)}/>}
    {cancel&&<Dialog title={t('لغو تحویل نقد','Cancel payout','Ödemeyi iptal et','Отмена выдачи')} onClose={()=>setCancel(null)}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api(`/cashouts/${cancel.id}/cancel`,'POST',{note:f.get('note')});setCancel(null);await wallet.reload();}catch(err:any){setError(err.code);}finally{setBusy(false);}}}><p>{t('فقط اگر وجه هنوز تحویل نشده، مبلغ به موجودی برگردد.','Release funds only if cash was not handed over.','Yalnızca nakit teslim edilmediyse tutarı serbest bırakın.','Верните средства, только если наличные не выданы.')}</p><label>{t('دلیل','Reason','Neden','Причина')}<input name="note" required maxLength={500}/></label><button className="ops-danger" disabled={busy}>{t('لغو و آزادسازی','Cancel & release','İptal ve serbest bırak','Отменить и вернуть')}</button></form></Dialog>}
    {showNew&&<Dialog title={t('ثبت مشتری سایت','Register customer','Müşteri kaydı','Регистрация клиента')} onClose={()=>setShowNew(false)}><form onSubmit={async e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);setBusy(true);try{const r=await api('/customers','POST',{displayName:f.get('name'),phone:f.get('phone')});await customers.reload();setSelected(r.username);setShowNew(false);}catch(err:any){setError(err.code);}finally{setBusy(false);}}}><label>{t('نام','Name','Ad','Имя')}<input name="name" required maxLength={100}/></label><label>{t('تلفن با پیش‌شماره کشور','Phone with country code','Ülke koduyla telefon','Телефон с кодом страны')}<input name="phone" dir="ltr" placeholder="+90…" required/></label><Notice error={error}/><button className="ops-primary" disabled={busy}>{t('ثبت مشتری','Create customer','Müşteri oluştur','Создать клиента')}</button></form></Dialog>}
  </Screen>;
}
